### ISSUE TITLE
missing NSG properties

### ISSUE THREAD

**Issue by flyingoverclouds** [Azure/migAz#103]
properties "sourceAddressPrefixes", "destinationAddressPrefixes" and "sourceAddressPrefix" missing for NSG exported in migration template. (and latest API 2017-06-01 not supported)

New-AzureRmResourceGroupDeployment : 1:38:02 PM - Error: Code=SecurityRuleParametersMissing; Message=Required security rule
parameters are missing for security rule with Id: /subscriptions/XXXXXXX/resourceGroups/RGNAME/providers/Microsoft.Network/networkSecurityGroups/MONNSGNAME/securityRules/SSH_FROM_LAN. Security rule must
specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups.

**Comment by rsanderson2350** [comment]
Did this occur on an ASM to ARM migration, or an ARM to ARM Migration?

**Comment by flyingoverclouds** [comment]
ARM (central us) to ARM (france central)

**Comment by HQJaTu** [comment]
The error says:
> specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups

If I have a list of `SourceAddressPrefixes`, the error is still emitted as `SourceAddressPrefix` is missing.

**Comment by ruandersMSFT** [comment]
#244
