### ISSUE TITLE
which steps after migration?

### ISSUE THREAD

**Issue by 4zap** [Azure/migAz#113]
Hi
Can please anyone tell me what steps are nessecary after the deployment is completed? I have the old and the new RG with the VMs and vnet inside. How do i commit the changes and switch to the new Vnet and VM's inside? I cant find anything in any documentation and a search did not bring me any results. Thanks a lot

**Comment by rsanderson2350** [comment]
There really aren't any steps to "commit".  If you have executed the MigAz script and you have your new RG with Azure ARM Resources, then they are "online".  

Is the condition that you had an ASM Virtual Network and ASM Virtual Machine and you migrated them to an ARM Virtual Network and ARM Virtual Machine?  Have you established either a [Site To Site ](https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-site-to-site-resource-manager-portal)or [Point to Site](https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-point-to-site-resource-manager-portal) VPN Connection to your new Azure Virtual Network to be able to access the VM resources via internal / private IP Addressing?

**Comment by 4zap** [comment]
Hi 
thanks for your reply. The ASM network which i migrated contains site2site VPN's to other Azure networks (USA, Asia which are still ASM) and onprem RAS Servers..... I wasnt keen enough to swich off the old vnet and all its vpn connections because i wasnt shure if i can connect and the new VMs working correctly and get the network back to a productive state. My main problem is that i have only a limited time frame for this job, so i must avoid a longterm outage and have no time for experiments or testing.
Next obstacle is the overlapping network scope... for the VPN Gateways and the VNET.  I will schedule it for a weekend shift and will first switch off the old vnet and connections and try to reestablish them with the new ARM vnet. Hope it will work....

**Comment by rsanderson2350** [comment]
If you have an overlapping / same IP Address space between the old and new VNets, you are correct that you not be able to bring VPN connectivity to both online at the same time.

Do plan in advance of your production migration, including an understanding of how long it will take to migrate.  

Given that you have conducted some test migrations (i.e. have a new VNet only and one or more VMs online in that new VNet), but have no S2S or P2S VPN connectivity, your only way to connect to a VM within that test/isolated Virtual Network will be to temporarily use a Public IP Address on a VM to log into it.  You can ensure you limit access (i.e. to your IP Address only) by using a Network Security Group to limit connections while you are temporarily using a Public IP Address.  Internal IP Addressing is not available to you, as you don't have any connectivity established to the VNet.  Longer term, establish your migration plan, including new VNet Creation, old S2S VPN remove, new S2S VPN established, VM Migration order, etc.

**Comment by 4zap** [comment]
Thanks again, i will prepare it and let you know how it ends. I did a test migration before with a test enviroment but with no VPN and Gateways.

**Comment by rsanderson2350** [comment]
Also, ensure you have a roll back plan, in the event you run into further migration challenges and/or identify you have insufficient time to complete a cold cut over (due to the same address space).

**Comment by rsanderson2350** [comment]
Checking in.  Were you able to complete the migration?

**Comment by 4zap** [comment]
Hi, yes. But it was a night shift... connected the new RG to all premises first with site2site VPN, edited all routes to the old networks and it workes! Now i have my network in a ASM RG and this made some things much more easier. Thanks for your support!
