### ISSUE TITLE
Migaz tool didn't generate the  BlobCopyFile jason when choosing the unmanaged disk in the destination

### ISSUE THREAD

**Issue by tzung27** [Azure/migAz#115]
I can get the all .jason csript (TemplateFile TemplateParameterFile BlobCopyFile) if the destination disk I choose to use managed disk in the distination resource group.
I just only got the TemplateFile jason when I choose to use unmanaged disk in the destination resource group.
Because it didn't generate the  BlobCopyFile jason,I can not copy the vhd to destination storage account.
I have tried serveral times and always can not get the TemplateParameterFile and BlobCopyFile jason file.

Could you help to solve this issue ?

Powershell command is below.
BlobCopyFile path is empty.

New-AzureRmResourceGroupDeployment -ResourceGroupName "asmtoarm" -TemplateFile "F:\Azure\MigAz\MigAz v2.3.1.0\asmtoarm\asmtoarm.json" -BlobCopyFile ""

Thanks a lot.

**Comment by rsanderson2350** [comment]
Should be resolved, please download v2.3.3.1

**Comment by tzung27** [comment]
Many thanks.
Regards,
