### ISSUE TITLE
Migration asm-arm

### ISSUE THREAD

**Issue by kostasbellis** [Azure/migAz#119]
Storage Account target name cannot exceed 22 character(s) due to Suffix character requirements.
   σε MigAz.Azure.MigrationTarget.StorageAccount.SetTargetName(String targetName, TargetSettings targetSettings)
   σε MigAz.Azure.MigrationTarget.StorageAccount..ctor(IStorageAccount source, TargetSettings targetSettings)
   σε MigAz.Azure.AzureSubscription.<BindAsmResources>d__166.MoveNext()
--- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
   σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   σε MigAz.Azure.UserControls.MigrationAzureSourceContext.<BindAsmResources>d__79.MoveNext()

**Comment by rsanderson2350** [comment]
Duplicate to #116 .  Please download v2.3.3.1.
