### ISSUE TITLE
Unable to enter credentials due to PromptBehavior.Auto

### ISSUE THREAD

**Issue by PaoloCastAway** [Azure/migAz#124]
The default value of **promptBehavior** parameter in method **LoginAzureProvider** is causing me trouble, since I always get authenticated with my current corporate account, while I need to enter different credentials. By simply changing the default value to **PromptBehavior.Always** I solved the issue

**Comment by rsanderson2350** [comment]
Added Login Prompt Behavior to options dialog, defaults to Always.  Released version 2.3.3.3.
