### ISSUE TITLE
busy: getting subscriptions

### ISSUE THREAD

**Issue by myossiv** [Azure/migAz#128]
hello
when I try to sing into the destination subscription it stuck at
busy: getting subscriptions
why?

**Comment by rsanderson2350** [comment]
I think I've observed this once or twice during development, but have not looked into this yet.  Am I correct that if you re-run the MigAz tool and connect it is not a reproducible issue (was one time / isolated)?

**Comment by myossiv** [comment]
it is happing again 
stuck in busy
see pic attached 
need help, please

![image](https://user-images.githubusercontent.com/10077097/36470701-7bfdfd52-16f4-11e8-96f6-1be89d7ec45a.png)

**Comment by rsanderson2350** [comment]
Testing with v2.4.0.0 has identified this may have been a "Ready" label wasn't the last message out of that routine, which has been added.  This is believe to be resolved.  Please advise / reopen in the event you are able to reproduce again.
