### ISSUE TITLE
60 minute timeout on the temporary storage blob

### ISSUE THREAD

**Issue by krhynerson** [Azure/migAz#131]
MigAz creates a shared access signature (SAS) that is valid for 60 minutes.

Is that timeout configurable?  If not, does MigAz automatically adjust that timeout based on the amount of resources to migrate?  

The concern is that we will run into potential timeout issues for migrating large VMs.

Thanks in advance

**Comment by rsanderson2350** [comment]
Yes, see the Managed Disk Access SAS Duration configuration option available in the File menu -> Options dialog.

<img width="449" alt="sasduration" src="https://user-images.githubusercontent.com/16927960/36451799-82be5cc2-164f-11e8-8532-9df2722f3c76.png">

**Comment by krhynerson** [comment]
Awesome, thanks!
