### ISSUE TITLE
Speeding Up MigAZ

### ISSUE THREAD

**Issue by mhamilt2** [Azure/migAz#133]
Hello,
Is there a way to enable a faster transfer of data to the source subscription? We have a project and are doing roughly 25 TB of managed disk from PAYG to Azure CSP subscription. Based on tests we estimate 1TB/HR. Would setting up a high performance site-site VPN speed up the process? Any recommendations on how to increase this speed?
Thank you,

**Comment by brandonmarcus** [comment]
You should look into Azure import/export to ship disk drives to the Azure datacenter. https://docs.microsoft.com/en-us/azure/storage/common/storage-import-export-service

**Comment by mhamilt2** [comment]
Hi Brandon,
I'm looking to decrease the amount of times the VM's are actually offline. I feel like this would lead to a longer amount of downtime. Any other methods you've run into?

**Comment by brandonmarcus** [comment]
Have you tried to turn off encryption temporarily while you transfer data. This will increase throughput. If you already have the high performance VPN SKU, then is there any chance of implementing expressroute? You can always try paying a third party to use their expressroute to increase throughput.

**Comment by ruandersMSFT** [comment]
#214
