### ISSUE TITLE
Virtual network button typo

### ISSUE THREAD

**Issue by silgit** [Azure/migAz#150]
Typo in the virtual network name. Spelled virutal instead of virtual.
![image](https://user-images.githubusercontent.com/36476784/37200869-f8342c8a-237d-11e8-9b60-9e94db718f28.png)

**Comment by rsanderson2350** [comment]
Side buttons have been moved in the code to be a right-click Context Menu within the Target Tree View.  Spelling has been verified on the new context menu, so proceeding to close.  Thanks.
