### ISSUE TITLE
Unable to pull any ASM resources

### ISSUE THREAD

**Issue by silgit** [Azure/migAz#151]
I am trying to list the ASM resources in my subscription but it keeps erroring out with:

`09/03/2018 09:44:28   ASM403ForbiddenExceptionDialog  <Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

The remote server returned an error: (403) Forbidden.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__14.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureRetriever.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureAsmResources>d__184.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 2057
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureASMRoleSizes>d__135.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 885
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<BindAsmResources>d__126.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 479
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<BindAsmResources>d__87.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 277
`
I am logged in correctly and it can list ARM resources no problem.
What can be the issue here?

**Comment by rsanderson2350** [comment]
Is this still occuring with the latest v2.4.2.1?  If so, have the source code line numbers changed from those above?

**Comment by fcommand** [comment]
Same problem for a customer sub where I'm contributor (works with my MS sub where I'm owner) 

10/04/2018 09:49:55   GetAzureRestResponse  ffa10bcc-5da5-436e-92f6-c91f111534cc Url: https://management.azure.com/subscriptions/fc66ea67-5c4c-4d7d-b4df-22cf6192828c/providers?&api-version=2017-05-10
10/04/2018 09:49:55   GetAzureRestResponse  ffa10bcc-5da5-436e-92f6-c91f111534cc Received REST Response
10/04/2018 09:49:55   GetAzureRestResponse  ffa10bcc-5da5-436e-92f6-c91f111534cc GET https://management.azure.com/subscriptions/fc66ea67-5c4c-4d7d-b4df-22cf6192828c/providers?&api-version=2017-05-10
10/04/2018 09:49:55   GetAzureRestResponse  49e67281-0d87-4e3f-aa97-42e1aeecb99d EXCEPTION Le serveur distant a retourné une erreur : (403) Interdit.
10/04/2018 09:49:55   GetAzureRestResponse  49e67281-0d87-4e3f-aa97-42e1aeecb99dhttps://management.core.windows.net/fc66ea67-5c4c-4d7d-b4df-22cf6192828c/rolesizes  EXCEPTION Le serveur distant a retourné une erreur : (403) Interdit.
10/04/2018 09:49:55   ASM403ForbiddenExceptionDialog  <Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

Le serveur distant a retourné une erreur : (403) Interdit.

   à MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__19.MoveNext() dans C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureRetriever.cs:ligne 196
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à MigAz.Azure.AzureSubscription.<GetAzureAsmResources>d__205.MoveNext() dans C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:ligne 2194
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à MigAz.Azure.AzureSubscription.<GetAzureASMRoleSizes>d__154.MoveNext() dans C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:ligne 968
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à MigAz.Azure.AzureSubscription.<BindAsmResources>d__145.MoveNext() dans C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:ligne 519
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à MigAz.Azure.UserControls.MigrationAzureSourceContext.<BindAsmResources>d__87.MoveNext() dans C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:ligne 271
10/04/2018 09:49:55   BindArmResources  Azure Subscription Child Initialization not yet started or not yet completed.  Skipping BindArmResources.

**Comment by rsanderson2350** [comment]
Recommend reviewing issue #47, #69 and #73. Historically, with regards to ASM permissions, users have needed to ensure the user account they are authenticating with has been granted co-administrator access to the ASM Subscription in the Azure Classic Portal.

https://docs.microsoft.com/en-us/azure/billing/billing-add-change-azure-subscription-administrator

See the "Azure classic portal" section.

**Comment by rsanderson2350** [comment]
Closed per no further response received, should be resolved by reviewing existing issues and utilizing account with sufficient permissions.
