### ISSUE TITLE
The tool stop on BUSY : Getting Virtual Machine XXX for Cloud Service XXX

### ISSUE THREAD

**Issue by Antse** [Azure/migAz#17]
Hello,

Version number 1.5.0.1

I'm trying to export an ASM VM template to move them to an new ARM subscription, but the tool stop on BUSY : Getting Virtual Machine XXX for Cloud Service XXX.

What can i do ? Is there a way to know what is happening ?

Thanks in advance,

**Comment by PauloRamosGit** [comment]
Hi antes,

Thank you for reporting the issue. To help us investigate it can you please send the logs files (C:\Users\<user>\AppData\local\MigAz\*.log) to support@migaz.tools?

Also, can you please try with v1.4.11.0 release and check if you also face the problem?
https://github.com/PauloRamosGit/migAz/raw/b8a30664c3c5312d66f1d9742254edda32cb6e96/asm/release/migAz%20ASM%20v1.4.11.0.zip

Regards

**Comment by Antse** [comment]
Paulo thanks for the quick feedback,

by using the 1.4.11.0 release, i'm not facing the same issue, i send your part of the logs though email.

KR,

**Comment by rsanderson2350** [comment]
MigAz v2.0.0.0 (which currently includes the next major update) should be released live within the next day, and this should be addressed in that build.  Thanks.

**Comment by rsanderson2350** [comment]
MigAz ASM to ARM v2.0.0.0 is now available - https://github.com/Azure/migAz/tree/master/release

**Comment by Antse** [comment]
Thanks, i will check and let you know if the issue still happenning

**Comment by PauloRamosGit** [comment]
Hi @Antse  , can you confirm if v2.0.0.0 solved this issue?

**Comment by rsanderson2350** [comment]
@Antse Version 2.1.0.0 is now available.  Please validate resolution against the latest version and advise if an issue is still occurring when retrieving Virtual Machine / Compute resources.  Thanks.

**Comment by PauloRamosGit** [comment]
Hi @Antse , we will temporary close this issue since this should be already solved on the latest release. Let us know if that is not the case

**Comment by Antse** [comment]
issue as been solved with the new version
