### ISSUE TITLE
ASM to ARM: Not able to scan classic resources form the subscription

### ISSUE THREAD

**Issue by bhatiarahul1993** [Azure/migAz#170]
I am trying to migrate VMs from ASM to ARM with in same subscription, but it doesn't list any ASM/classic resource in source resource list from my subscription. It is not able to detect any ASM/classic resources from my subscription. On completion of the scan for ASM resources, it shows nothing on the list of available resources to migrate.

**Comment by rsanderson2350** [comment]
I would recommend reviewing issue #47, #69 and #73.  Historically, with regards to ASM permissions, users have needed to ensure the user account they are authenticating with has been granted co-administrator access to the ASM Subscription in the Azure Classic Portal.

https://docs.microsoft.com/en-us/azure/billing/billing-add-change-azure-subscription-administrator

See the "Azure classic portal" section.

Also, ensure you do have ASM to ARM Selected:

![untitled](https://user-images.githubusercontent.com/16927960/39535770-a21cbd3a-4de9-11e8-9ba4-4530c7ee15ee.png)

**Comment by bhatiarahul1993** [comment]
thanks @rsanderson2350 for the help. It was an issue with Powershell.  I reinstalled the Azure powershell module and it worked.
