### ISSUE TITLE
Error: Target Resource Group must be provided for template generation

### ISSUE THREAD

**Issue by muapem** [Azure/migAz#171]
The error indicated in the subject: "Target Resource Group must be provided for template generation" indicates that I must enter the destination resource group. But I can not find where to enter this parameter.

Thanks for your help.

![targetresourcegroupmustbeprovided](https://user-images.githubusercontent.com/39072171/39732868-22761cc8-5246-11e8-9755-9d3e52a35fa3.jpg)

**Comment by rsanderson2350** [comment]
The resource group will show up in the "Target Resources" Pane.  It appears the subscription you connected to has not ARM Resources.  Once you select a source resource (you'll have to see them in the Source Tree View), it will appear.

**Comment by muapem** [comment]
Hi rsanderson2350. Thanks for you answer.
You are right. The origin does not have ARM resources, it is a classic virtual machine.
When I change the option for [Source Resource Type: Azure Service Management (ASM / Classic)] this log appears:
7/5/2018 22:43:21   ASM403ForbiddenExceptionDialog  <Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

Error en el servidor remoto: (403) Prohibido  = Error in the remote server: (403) Prohibited
I disabled the firewall but the error continues.

Any ideas?

**Comment by rsanderson2350** [comment]
Please refer to issue #170

**Comment by muapem** [comment]
Thaks for your help rsanderson2350
The reason for the error was indeed that the user must be a co-administrator

Best Regards!
