### ISSUE TITLE
Classic VM to ARM VM migration issue

### ISSUE THREAD

**Issue by chillryan** [Azure/migAz#176]
I'm trying to use MigAz to migrate classic to ARM. After having just done an ARM to ARM, I've noticed several things about classic to ARM. For one, when configuring any network related items (load balancer, nic, public ip) I'm not able to use "VNet in MigAz Migration" option. I attempted to create these objects on the subscription itself, but there are still items I can't configure.

I received the following error when I was attempting to address "Error: Target Virtual Network for Virtual Machine 'VM-name' Network Interface 'CobbSuperior-NIC1' must be specified." I used the 'Exisiting VNets(s)' option since 'Vnet in MigAz Migration' has empty drop downs.

EDIT: When manually creating virtual network, I can assign the NIC but the subnet isn't populated in the dropdown which prevents me from correcting the error.

Object reference not set to an instance of an object.
   at MigAz.Azure.UserControls.NetworkSelectionControl.<rbExistingARMVNet_CheckedChanged>d__19.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\NetworkSelectionControl.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by markgould** [comment]
Same issue here.

**Comment by rsanderson2350** [comment]
Code fix added on #184.
