### ISSUE TITLE
Unable to migrate a storage account

### ISSUE THREAD

**Issue by fcommand** [Azure/migAz#178]
For ASM to ARM migration, if i select only one classic storage account (sa) to migrate, there is always an error saying that the sa exists in target environment (different subscription in my case) but sa doesn't exist ; any name change for target gives the same error.

Example 
Target Name for Storage Account 'fcosasxxyyuu9999fco' already exists within Azure Environment AzureCloud.  A new (available) target name must be specified.
--

Version of MigAz used: 2.4.2.4

**Comment by rsanderson2350** [comment]
Version 2.4.2.5 includes more verbose output into the log file.  **The logic was not changed**, only the addition of more verbose output to the log file.

If you are still encountering this issue, please feel free to reply back / open the issue again if you are still encountering this issue.  You should see the following output in the log files with v2.4.2.5:

**Allowable Storage Account Name (nameAvailable = true):**

7/5/2018 4:05:27 PM   CheckNameAvailability  HttpStatusCode: 'OK
7/5/2018 4:05:27 PM   CheckNameAvailability  Response:  '{"nameAvailable":true}

**Invalid (already exists) Storage Account Name (nameAvailable = false):**

7/5/2018 4:10:34 PM   CheckNameAvailability  HttpStatusCode: 'OK
7/5/2018 4:10:34 PM   CheckNameAvailability  Response:  '{"nameAvailable":false,"reason":"AlreadyExists","message":"The storage account named test is already taken."}
