### ISSUE TITLE
DuplicateResourceName - /resourceGroups/providers/Microsoft.Network/loadBalancers/ has two child resources with the same name (default)

### ISSUE THREAD

**Issue by GustiM** [Azure/migAz#181]
I try a migration ASM to ARM.
I get the error attached.

I am attaching also the files generated by exporting objects.

**Comment by rsanderson2350** [comment]
I promptly removed your attached files, as they did include your Storage Account Keys.  Please do not post full account details (including but not limited to Azure Storage Account Keys) which could allow someone else to access your storage account.

The error output from the Resource Group Deployment in your files is identifying you have a Load Balancer with the same name.

New-AzureRmResourceGroupDeployment : 8:50:04 PM - Resource Microsoft.Network/loadBalancers 'AZCGLGWDEV08-lb' failed with 
message '{
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "DuplicateResourceName",
        "message": "Resource /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers/ has two child resources 
with the same name (default)."
      },
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.frontendIPConfigurations[2].properties.subnet."
      },
      {
        "code": "DuplicateResourceName",
        "message": "Resource /subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers/ has two child resources 
with the same name (default)."
      }
    ]
  }
}'
At C:\MigAz v2.4.2.4\Migrations\MigAz.ps1:331 char:3
+         New-AzureRmResourceGroupDeployment -ResourceGroupName $Resour ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCm 
   dlet
 
New-AzureRmResourceGroupDeployment : 8:50:04 PM - Resource 
/subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers/ has two child resources with the same name (default).
At C:\MigAz v2.4.2.4\Migrations\MigAz.ps1:331 char:3
+         New-AzureRmResourceGroupDeployment -ResourceGroupName $Resour ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCm 
   dlet
 
New-AzureRmResourceGroupDeployment : 8:50:04 PM - Value for reference id is missing. Path 
properties.frontendIPConfigurations[2].properties.subnet.
At C:\MigAz v2.4.2.4\Migrations\MigAz.ps1:331 char:3
+         New-AzureRmResourceGroupDeployment -ResourceGroupName $Resour ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCm 
   dlet
 
New-AzureRmResourceGroupDeployment : 8:50:04 PM - Resource 
/subscriptions//resourceGroups//providers/Microsoft.Network/loadBalancers/ has two child resources with the same name (default).
At C:\MigAz v2.4.2.4\Migrations\MigAz.ps1:331 char:3
+         New-AzureRmResourceGroupDeployment -ResourceGroupName $Resour ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCm 
   dlet
 
New-AzureRmResourceGroupDeployment : 8:50:38 PM - Template output evaluation skipped: at least one resource deployment 
operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
At C:\MigAz v2.4.2.4\Migrations\MigAz.ps1:331 char:3
+         New-AzureRmResourceGroupDeployment -ResourceGroupName $Resour ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCm 
   dlet
 
New-AzureRmResourceGroupDeployment : 8:50:38 PM - Template output evaluation skipped: at least one resource deployment 
operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
At C:\MigAz v2.4.2.4\Migrations\MigAz.ps1:331 char:3
+         New-AzureRmResourceGroupDeployment -ResourceGroupName $Resour ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCm 
   dlet
