### ISSUE TITLE
Choose 'None' for Availability set but it still creates line for creating one in JSON

### ISSUE THREAD

**Issue by recintoit** [Azure/migAz#183]
I don't want to migrate over the VMs with an availability set.  When I choose None in the VM options, it still puts this line in the JSON.  Is this ok or should it be commented out before I run the .ps1?  
I would think if 'None' is chosen it would not create a resource for the Availability Set.
Is it mandatory to create one in ARM even though I have one in there?

{
      "type": "Microsoft.Compute/availabilitySets",
      "apiVersion": "2017-03-30",
      "name": "VMName-as",
      "location": "[resourceGroup().location]",
      "tags": {
        "migAz": "RemovedthisID"
      },
      "sku": {
        "name": "Aligned"
      },
      "properties": {
        "platformUpdateDomainCount": 5,
        "platformFaultDomainCount": 3
      }
    },

**Comment by recintoit** [comment]
I receive this error after the blob copy and I do not know if it is due to the deployment trying to create the Availability Set.  I've migrated VMs with earlier versions.

Test-AzureRmResourceGroupDeployment : A parameter cannot be found that matches parameter name 'Confirm'.
At D:\Azure\MigAz\MigAz2_4_2_4\MigAz.ps1:353 char:112
+ ... esourceGroupName -TemplateFile $TemplateFile -Debug -Confirm:$false - ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-AzureRmResourceGroupDeployment], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.TestAzureResourceGroupDeployme 
   ntCmdlet

**Comment by recintoit** [comment]
![migaz_confirmerror](https://user-images.githubusercontent.com/35378940/41069105-528482c0-69a1-11e8-8a54-b4381156a413.JPG)

**Comment by recintoit** [comment]
Update:  The VM is migrated and created.  In the Resource Group, I see the VM, NIC, and Availability Set, but NO disks.  Is the Migration not adding the disks to the resource group?

**Comment by recintoit** [comment]
After the VMs are created there is a MigAz storage account that looks like it still houses the disks that were copied but they are not managed disk.  I think the other issue I have from the screenshot above is due to an error removing the temp storage account.  I ran a migration in version 2.4.2.1 and it that part works with no issue and I do not get the 'Confirm' error or ActiveDirectory Token messages when in Debug.

**Comment by rsanderson2350** [comment]
The inclusion of the -confirm switch on the call to Test-AzureRmResourceGroupDeployment has been removed.  You will need to run the Test-AzureRmResourceGroupDeployment command against the RM Template to identify more detailed error about why the VM failed to provision.  I know you said the VM, NIC and Availability Set provisioned; however, something did not provision successfully (likely related to the Managed Disk(s), as you stated).  

The temporary MigAz Storage Account that contains the VHD(s) can be deleted after your VM in running (it is just temporary storage for initial provisioning of the VM).  This storage account is normally deleted via the MigAz.ps1 PowerShell; however, this is only executed upon a successful deployment (no error on Resource Group Deployment).

Closing this issue based on the original title/scope being related to None / Availability Sets.  If you can identify an error from the Test-AzureRmResourceGroupDeployment output that you would like further assistance on, please open this as a new issue.
