### ISSUE TITLE
update documentation and files

### ISSUE THREAD

**Issue by frfriel** [Azure/migAz#185]
![image](https://user-images.githubusercontent.com/22626075/41172498-a85596c0-6b19-11e8-8c69-3116e6bea0c2.png)

As shown above, in Step 9 of the ASM > ARM migration instructions there is a reference to the BlobCopy.psi.  This file appears to have been replaced by BlobCopy_Delete_Snapshots.ps1

Can someone validate this? Thank you.

**Comment by ruandersMSFT** [comment]
#241
