### ISSUE TITLE
Setting Environment for Sovergin Clouds

### ISSUE THREAD

**Issue by shawnweisfeld** [Azure/migAz#19]
First thank you for your support of Sovereign Clouds!

The instructions that get generated tell you to do the following for logging into the Sovereign Cloud
Login-AzureRmAccount -Environment "AzureUSGovernment"

This should be 
Login-AzureRmAccount -EnvironmentName AzureUSGovernment

Per the documentation here:
https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-get-started-connect-with-ps

I think the resolution is a tweak to Line 180 in the following file:
https://github.com/Azure/migAz/blob/master/asm/source/MigAz.Azure/Generator/AsmToArm/TemplateResult.cs

From: 
instructionContent = instructionContent.Replace("{migAzAzureEnvironmentSwitch}", " -Environment \"" + _TargetSubscription.AzureEnvironment.ToString() + "\"");

To:
instructionContent = instructionContent.Replace("{migAzAzureEnvironmentSwitch}", " -EnvironmentName " + _TargetSubscription.AzureEnvironment.ToString());

**Comment by rsanderson2350** [comment]
Shawn,

MigAz v2.0.0.0 (which currently includes the next major update) should be released live within the next day, and this should be addressed in that build.  Thanks.

**Comment by rsanderson2350** [comment]
MigAz ASM to ARM v2.0.0.0 is now available - https://github.com/Azure/migAz/tree/master/release

**Comment by shawnweisfeld** [comment]
@rsanderson2350  Tested with MigAz ASM to ARM v2.0.0.0. it works. Thank you for the quick turnaround!
