### ISSUE TITLE
Source storage account SAS URL 

### ISSUE THREAD

**Issue by jezlloyd** [Azure/migAz#190]
We have a large VM to copy over and the default 60 minutes SAS generated on the source storage account isn't long enough. The job reaches that limit and cancels.

**Comment by rsanderson2350** [comment]
Looks like you must have figured out the resolution.  You can increase the duration for which the SAS Token is valid for within the Options Dialog from the File Menu.  Simply increase the duration via the Options dialog, and your SAS Token will be valid for a longer period of time, which may be necessary for large blob copy operations.
