### ISSUE TITLE
Unhandled exception: AADSTS50074: Strong Authentication is required.

### ISSUE THREAD

**Issue by swieder** [Azure/migAz#192]
AADSTS50074: Strong Authentication is required.
Trace ID: 90ee098a-5312-4b55-ae1e-beee1d940300
Correlation ID: 98a42dde-8597-40fa-93c6-32f0796931c5
Timestamp: 2018-07-09 15:13:28Z
   at MigAz.Azure.UserControls.AzureArmLoginControl.<btnAuthenticate_Click>d__5.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\UserControls\AzureArmLoginControl.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment]
Is the account you are using setup for Multi Factor Authentication?

**Comment by swieder** [comment]
Yes…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rsanderson2350** [comment]
I use MFA with MigAz frequently.  Do you have Active Directory Premium in use here?  Any insight into what "Strong Authentication" requirement you are not meeting with the login process?

**Comment by swieder** [comment]
Might be a bit of a one off.  I’m using a B2B account and both the inviting directory and my home directory require me to use MFA so I have to do it twice.

Was able to work around it by force a re-sign on (don’t pick my existing account in list) and while it gave the error again, I closed it and it was able to access everything.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rsanderson2350** [comment]
@2011ComputerMan were you also using a B2B Account scenario when you encountered this?

**Comment by ruandersMSFT** [comment]
@ctraynor-lightstream Moving your issue to this thread.  Please review the thread.  Have been unable to reproduce the issue.  Do you have any inputs your can provide about the subscription setup that may be causing "Strong Authentication is required" that could be tested?

**Comment by ctraynor-lightstream** [comment]
I am also using MFA like the others on the thread.  It is B2B connection.  I have a lot of tenants that load.  I get about half loaded and then the error.  I am not getting which subscription/tenant is the one that fails.  I can select one of the ones that loads and work with that one.  I think it is a newer tenant and may be a tenant where both my tenant and the B2B linked tenant both require MFA.


Chris Traynor
Principal Cloud Architect
Office | (303) 689 - 1851
Mobile | (720) 988 - 0720

chris.traynor@lightstream.tech<mailto:chris.traynor@lightstream.tech>
https://www.lightstream.tech

[signature_1897870925]

**Comment by ctraynor-lightstream** [comment]
I am also using MFA like the others on the thread.  It is B2B connection.  I have a lot of tenants that load.  I get about half loaded and then the error.  I am not getting which subscription/tenant is the one that fails.  I can select one of the ones that loads and work with that one.  I think it is a newer tenant and may be a tenant where both my tenant and the B2B linked tenant both require MFA.

**Comment by ruandersMSFT** [comment]
Ok.  I have subscriptions where I am using MFA Authentication, and have not been able to get this error to occur.  The content mentioned that several tenants seem to load and then failure occurs on a particular tenant is good context.  I'll look to add some try/catch surrounding the tenant and subscription loading so that a failure on one particular tenant/subscription no longer causes all tenants/subscriptions to fail as a whole.

**Comment by ruandersMSFT** [comment]
Please download release v2.4.4.4 and advise if the added error handling surrounding Tenants, Domains and Subscriptions helps successfully load.

https://github.com/Azure/migAz/releases/tag/v2.4.4.4

**Comment by ctraynor-lightstream** [comment]
2.4.4.4 solved the issue for me.  I got a second authorization push to the Authenticator App.  I was not getting that before.  All Tenants loaded as well.

**Comment by ruandersMSFT** [comment]
Wonderful!  Thanks for that tidbit about some subscriptions load, then failure occured.  Proceeding to close for now.
