### ISSUE TITLE
ARM VirtualMachine null OSDisk object observed in Resource Group with more than 50 Managed Disks

### ISSUE THREAD

**Issue by ruandersMSFT** [Azure/migAz#196]
Observed occurring in a resource group that contained 56 managed disks.  Only 50 managed disks were observed to have been loaded, resulting in an object reference from the VM to the Managed Disk for the OS volume being null (could not find the specified Managed Disk By Id).

**Comment by rsanderson2350** [comment]
Consideration of moving towards batch API querying in MigAz
