### ISSUE TITLE
Public Load Balancer must have either a Public IP association.

### ISSUE THREAD

**Issue by vimalv4u** [Azure/migAz#200]
HI I am receiving the error when i try to move the VM from classic to resource manager. The Public IP option in empty.
I cannot Export the configuration without mediating this error.  If i select private IP, i can see the option to attach or migrate to a virtual network with private IP. Version used is Release_v2.4.3.1.

The Screen clip is below
https://v4luhome-my.sharepoint.com/:i:/p/vimalv4u/ESocLFqeKIhLnR3SLHhpHmMB57oDRxNpc2uylU6OQ-S1kQ?e=pSIrcN

**Comment by vimalv4u** [comment]
HI 
Thanks for that. Can get a release compiled with the module. Sorry to bug you.

**Comment by rsanderson2350** [comment]
Encountering issue #181 while testing load balancer deployment

**Comment by rsanderson2350** [comment]
New release should be good on using a Public IP that is in the migration template (new Public IP created by ARM Template).  Have not yet has time to test against an existing Public IP, so will leave issue open for said testing / change.

**Comment by rsanderson2350** [comment]
@vimalv4u Should be good with a new Public IP (you can also right click on the Resource Group in the Target Tree View to add a new Public IP).  Will work on using an existing ARM Public IP soon.

**Comment by ruandersMSFT** [comment]
#245
