### ISSUE TITLE
migrate Public IP from ARM to CSP

### ISSUE THREAD

**Issue by mauriziomancini** [Azure/migAz#206]
hello everybody.
does anyone know if the new release (2.4.4) correctly migrate a public IP address from ARM to CSP?
thanks in advance for your feedback
cheers

**Comment by Brucius** [comment]
nope, public IP addresses can't be migrated as Azure automatically assigns new IP addresses upon creation.

**Comment by ruandersMSFT** [comment]
@mauriziomancini Does that answer the question for issue closure?  The deployment of a new Public IP ARM object, within the same or different Azure Environment, will result in the allocation of a different IP address.

**Comment by mauriziomancini** [comment]
Yes.
Thank you so much for your response .
Cheers



Sent from Libero Mail for iOS


Saturday, 8 September 2018, 02:33 +0200 from notifications@github.com  <notifications@github.com>:
