### ISSUE TITLE
Workaround for Access Token expiry

### ISSUE THREAD

**Issue by Brucius** [Azure/migAz#207]
Hi, I just wanna check if we could do something from the old deployment type like below where we could login and select the subscription ID instead of using the access token as it is sort of messing up with the incremental New-ResourceGroupDeployment after copying the blob and running a part of the command without the blob copy part. Really appreciate it! @ruandersMSFT 

```
& 'path' -ResourceGroupName "RGName" -ResourceGroupLocation "region" -TemplateFile "path" -TemplateParameterFile "path"
```

Below the reference deployment instruction from version 2.4.2.5. I noticed the change in version 2.4.3.0.
```
Open Azure PowerShell and sign into your target subscription.
Login-AzureRmAccount -TenantId 'xxxx-xxxx-xxxx-xxxx' -SubscriptionId 'yyyy-yyyy-yyyy-yyyy'
Select-AzureRmSubscription -SubscriptionId 'yyyy-yyyy-yyyy-yyyy'


Deploy your ARM Resources to the new 'RGName' Resource Group with the following PowerShell command:
& 'path' -ResourceGroupName "RGName" -ResourceGroupLocation "region" -TemplateFile "path" -TemplateParameterFile "path" -BlobCopyFile "path"
```

**Comment by Brucius** [comment]
Nevermind, found a work around. For those of us who are facing the same issue, the work around is to take away the `-AccountID` and `-AccessToken` from the string.
```
& 'C:\path' -TenantId 'xxxx-xxxx-xxxx-xxxx' -SubscriptionId 'yyyy-yyyy-yyyy-yyyy' -AccountId 'abc@mail.com' -AccessToken 'tokenid' -ResourceGroupName "targetRG" -ResourceGroupLocation "region" -TemplateFile "path" -TemplateParameterFile "path" -BlobCopyFile "path"
```

**Comment by Brucius** [comment]
Sorry, just tested the string again and it stopped working after a while when the access token expires.

**Comment by ruandersMSFT** [comment]
Token expiry duplicate to #205.

**Comment by Brucius** [comment]
Thanks, Will test out the new call method.

**Comment by ruandersMSFT** [comment]
@ickacn Closing #205 as duplicate to this.  Monitor here.

**Comment by Brucius** [comment]
Tested out, so you'll have to open up a new POSH terminal and login again in order to run the string for incremental deployment.

**Comment by ByronZA** [comment]
@Brucius, i'm literally busy with an ARM CSP to CSP migration and faced the same problem.

Could I ask kindly for you to assist me with providing the pwershell commands required in sequence to resolve this?

**Comment by ruandersMSFT** [comment]
@ByronZA Consider removing the AccountId and AccessToken parameters from the launch of the MigAz.ps1 command.  It should prompt you for authentication, allowing you to obtain an access token with access to refresh, valid for the duration of your script need.

**Comment by Brucius** [comment]
@ByronZA like what @ruandersMSFT said, you'll have to start a new session for Posh terminal and login, select target subscription and run the deployment command without account ID and access token parameters.

**Comment by Brucius** [comment]
@ByronZA ahh yes, the 3rd party marketplace items in CSP subscriptions cannot be deployed with Powershell it seems even with the PS commandlet: 
```
Set-AzureRmMarketplaceTerms
```
What I did was manually provision the servers from portal and reattach the disks.

**Comment by eosho** [comment]
I am having this issue too, while trying to migrate classic from one subscription to another subscription. ```
New-AzureRmResourceGroupDeployment : The access token expiry UTC time '11/23/2018 6:38:00 PM' is earlier than current UTC time 
'11/23/2018 7:08:23 PM'.
```

Any ideas how to resolve it??

**Comment by Brucius** [comment]
@eosho 
Try opening up a new power-shell terminal and running the command again.
Make sure you're logged in and set to correct context.
```
Login-AzureRMAccount
Set-AzureRMContext
```

**Comment by ruandersMSFT** [comment]
I'll revise my response tomorrow as i don't have the exact powershell in front of me.   Consider removing 2 or 3 parameters from the launching of the MigAz.ps1 script.   Specifically, look to remove the parameter that contains the username and the access token for sure.   If that is not enough, the tenant id may also need to be removed.   This will trigger the script to prompt you for account authentication,  which will have access to the refresh token.  Your blob copy is likely on a large ( >= 1TB ), and the existing token is expired by the time the asynchronous copy completes.

**Comment by ickacn** [comment]
> 我也遇到了這個問題，同時嘗試將classic從一個訂閱遷移到另一個訂閱。``` 
> 任何想法如何解決？
> 
> ```
> New-AzureRmResourceGroupDeployment : The access token expiry UTC time '11/23/2018 6:38:00 PM' is earlier than current UTC time 
> '11/23/2018 7:08:23 PM'.
> ```

Get a new token
Then replace the original token
After execution, you will be asked if you want to replace vhd and answer no.
You can continue to the end to the end.

> I am having this issue too, while trying to migrate classic from one subscription to another subscription. ```
> Any ideas how to resolve it??
> 
> ```
> New-AzureRmResourceGroupDeployment : The access token expiry UTC time '11/23/2018 6:38:00 PM' is earlier than current UTC time 
> '11/23/2018 7:08:23 PM'.
> ```

Get a new token
Then replace the original token
After execution, you will be asked if you want to replace vhd and answer no.
You can continue to the end to the end.

**Comment by eosho** [comment]
> I'll revise my response tomorrow as i don't have the exact powershell in front of me. Consider removing 2 or 3 parameters from the launching of the MigAz.ps1 script. Specifically, look to remove the parameter that contains the username and the access token for sure. If that is not enough, the tenant id may also need to be removed. This will trigger the script to prompt you for account authentication, which will have access to the refresh token. Your blob copy is likely on a large ( >= 1TB ), and the existing token is expired by the time the asynchronous copy completes.

@ruandersMSFT I tired that method from the above discussions and it didn't work for me. My disk is only 130GB os disk. I am trying to migrate from one subscription to another (classic to ARM).

**Comment by eosho** [comment]
> > 我也遇到了這個問題，同時嘗試將classic從一個訂閱遷移到另一個訂閱。```
> > 任何想法如何解決？
> > ```
> > New-AzureRmResourceGroupDeployment : The access token expiry UTC time '11/23/2018 6:38:00 PM' is earlier than current UTC time 
> > '11/23/2018 7:08:23 PM'.
> > ```
> 
> Get a new token
> Then replace the original token
> After execution, you will be asked if you want to replace vhd and answer no.
> You can continue to the end to the end.
> 
> > I am having this issue too, while trying to migrate classic from one subscription to another subscription. ```
> > Any ideas how to resolve it??
> > ```
> > New-AzureRmResourceGroupDeployment : The access token expiry UTC time '11/23/2018 6:38:00 PM' is earlier than current UTC time 
> > '11/23/2018 7:08:23 PM'.
> > ```
> 
> Get a new token
> Then replace the original token
> After execution, you will be asked if you want to replace vhd and answer no.
> You can continue to the end to the end.

@ickacn how do I go about generating a new token ?

**Comment by ruandersMSFT** [comment]
Please download v2.4.4.2 to pickup the code change above to the MigAz.ps1 file.  As mentioned previously, look to remove the AccountId and AccessToken parameters from the launch of MigAz.ps1, which should successfully trigger (using the new MigAz.ps1) an Azure Login Prompt.  One additional key note, ensure you launch MigAz.ps1 in a new PowerShell session (not in an existing PowerShell session in which you utilized MigAz.ps1 with the AccountId and AccessToken parameters supplied).

**Comment by eosho** [comment]
> Please download v2.4.4.2 to pickup the code change above to the MigAz.ps1 file. As mentioned previously, look to remove the AccountId and AccessToken parameters from the launch of MigAz.ps1, which should successfully trigger (using the new MigAz.ps1) an Azure Login Prompt. One additional key note, ensure you launch MigAz.ps1 in a new PowerShell session (not in an existing PowerShell session in which you utilized MigAz.ps1 with the AccountId and AccessToken parameters supplied).

@ruandersMSFT works now. thanks
