### ISSUE TITLE
Wrong TargetEndpoint for  China Azure

### ISSUE THREAD

**Issue by chenxin21cn** [Azure/migAz#212]
The TargetEndpoint in generated *_BlobCopy.json  file is wrong ("core.chi acloudapi.cn", should be "core.chinacloudapi.cn")!
I met this problem in  v2.4.4.1, ARM migration.

**Comment by chenxin21cn** [comment]
@ruandersMSFT  Where can I get this release? The latest is still v2.4.4.1 on the download page.

**Comment by ruandersMSFT** [comment]
Merged with v2.4.4.2
