### ISSUE TITLE
Always show Storage Account already exist when Transfer to diff Subscription

### ISSUE THREAD

**Issue by bryan543** [Azure/migAz#213]
As title, even if I change another Subscription or rename  Storage Account , Still got the same result.
If Transfer in the same Subscription, It's can be work
Pls confirm this Error，TKS~
(version : 2.4.4.1)

**Comment by ruandersMSFT** [comment]
Photo taken offline, for consideration of actual tenant/usernames being shown.  Will review.

**Comment by ruandersMSFT** [comment]
Bryan, a couple of thoughts:

1)  The image you included showed you were migrating your VM to a Classic Disk.  My recommendation would be to migrate to an Azure Managed Disk, which is certainly common place today across Azure Environments.  
2)  The indication that an Azure Storage Account of the same name (by error Storage Account already exists) could indicate a storage account that is in use in a different subscription or even tenant (that storage account is in use already within the Azure Environment).
3)  If you migrate the VM to Managed Disks, you won't have to worry about Storage Accounts anymore, as Azure self manages the disks across Storage Accounts.

Hope this helps.

**Comment by ruandersMSFT** [comment]
Also, see reply on #178 which shows the output you should see in the MigAz Log.  As you change the target name, you should see output in the log showing that the Storage Account name is or is not already in use within the Azure Environment.  Keep in mind the Storage Account name can already exist in someone else's subscription within the same Azure Environment.
