### ISSUE TITLE
Some of the Disks and NSGs are missing in the selection

### ISSUE THREAD

**Issue by Brucius** [Azure/migAz#220]
So using the tool for migrating to CSP and it seems some of the VMs have OS disks missing if it's more than 6 disk attached to it and if the NSGs have more than a few hundred security rules, they're not shown during the selection to generate the scripts.

**Comment by ruandersMSFT** [comment]
@Brucius Look back to #196, could the missing Disks be attributed to this being a Resource Group with more than 50 Managed Disks within it?  I'll have to run a separate test on a NSG with > 200 rules.

**Comment by Brucius** [comment]
yep @ruandersMSFT , missing disks are observed in Resource Groups with more than 100 disks. As for the NSGs, it seems the JSON template generation from portal seems to be broken on all of the NSGs with above > 200 rules. That maybe the cause of MigAz not recognising them in template generation.

<img width="1298" alt="screen shot 2018-10-05 at 12 31 32 pm" src="https://user-images.githubusercontent.com/7734956/46516295-81533480-c89b-11e8-95b9-cc3d6cc1cd38.png">
