### ISSUE TITLE
Get VM migrated to the ARM environment

### ISSUE THREAD

**Issue by wsy8789** [Azure/migAz#221]
Hi , Thank you for the great thing, migaz

I need to do the VM migration things next week. Move the vms from China East to China East 2 area.

ASM-ARM
ASM(ARM)-ARM
ARM-ARM
Load Balance

Situation listed below,

1,ARM VM(EAST) -ARM(EAST2) should be work great. Test already
2, Some VMs have been migrated from ASM to ARM, but the cloud service changed to load balancer.
3, Because the downtime is very short for us ,so we try  to use ASR and migaz for my project

My questions, Can you confirm below ?

a,  the NAT rules can't be migrated by migaz ,is it ?
b,  the backend pool connected VMs info on load balancer doesn't work after LB migrated,right ?

If yes ,we need manually set up NAT and backup pool connection back after migration.

We can migrate VM by ASR ( the speed is fast , few minutes for VHDs) , other things via migaz. Do you have any good ideas for the ASM VMs (which migrated to ARM already)?  NAT rules , NSG rules, how to make it easier?  

Thanks for everything.

**Comment by chenxin21cn** [comment]
I found no NAT rules exported in my testing using v2.4.4.1. Can you help to repair this bug?

**Comment by chenxin21cn** [comment]
If source LB is ASM,  everything is ok. But if source LB is ARM, no NAT rule  in the template output.  And backend pool is also not configured correctly with Avset/Network interface.

**Comment by ruandersMSFT** [comment]
#242
