### ISSUE TITLE
Hi i want to migrate into an exisiting storage account. The option in migaz is greyed out and wont let me select it. If i create a new storage account it says it already exisits? Any help please

### ISSUE THREAD

**Issue by mlunn82** [Azure/migAz#232]

**Comment by Brucius** [comment]
Have you got any more details around this?

**Comment by ruandersMSFT** [comment]
Look for v 2.4.4.3 in about 15 minutes.  Previous release (v2.4.4.2) had some of the object loading code accidentally commented out, and was likely the cause.  Please advise if it is still not working.

**Comment by mlunn82** [comment]
Hi, Thank you I have downloaded the latest release and will test it later on. Is there a way to migrate and keep the same public IP address from ASM to ARM?

**Comment by Brucius** [comment]
@mlunn82 You can always replicate the Vnet, NIC, NSG configurations into target and detach the public IPs from the source machines to re-attach them in the target.
