### ISSUE TITLE
Error in Deploy to Azure

### ISSUE THREAD

**Issue by chasquad** [Azure/migAz#235]
I get an error when trying to deploy via the Azure deployment button on this page: 
https://github.com/VirtoCommerce/vc-platform

Error code
InvalidTemplateDeployment
Message
The template deployment 'aa1bddfa-b937-4e8b-93b1-2ab68a4110da' is not valid according to the validation procedure. The tracking id is '0ee68472-1cc5-4801-9a4c-648da6e570cf'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.

**Comment by ruandersMSFT** [comment]
Comment posted on wrong GitHub Repo.
