### ISSUE TITLE
Unable to use "-" when creating vnet or subnet

### ISSUE THREAD

**Issue by eosho** [Azure/migAz#236]
When renaming a VNET or Subnet using "demovnet-01" or "demosubnet-01" the changes do not apply with the dash "-". It works well when creating a public IP address (see screenshot below).

![image](https://user-images.githubusercontent.com/10321481/55110464-75a83400-50ae-11e9-924e-357771c53dfe.png)

Other questions - will this tool eventually support migration to different azure regions and support more resource types?

**Comment by ruandersMSFT** [comment]
I'll look over the VNet config, will be releasing an updated version next Tuesday (4/2/19).  The tool already supports several Azure Regions.  What other/different azure regions are you looking for?  What other resource types are you looking for the tool to assist with?  Thanks

**Comment by eosho** [comment]
> I'll look over the VNet config, will be releasing an updated version next Tuesday (4/2/19). The tool already supports several Azure Regions. What other/different azure regions are you looking for? What other resource types are you looking for the tool to assist with? Thanks

Apologies, you are correct. I am able to copy resources to other regions. 

I want to be able to migrate the following - 
Microsoft.keyvaults
Microsoft.eventhub/*
Microsoft.web/sites*
Microsoft.DataFactory/datafactories
Microsoft.StreamAnalytics/streamingjobs
Microsoft.DocumentDB/databaseAccounts
Microsoft.Logic/workflows

**Comment by ruandersMSFT** [comment]
Added to Dev, releasing fix for "-".
