### ISSUE TITLE
"Too many requests received" error

### ISSUE THREAD

**Issue by artemaes** [Azure/migAz#24]
I see the error each time trying to get the list of resources from ASM subscription in MigAZ.
The subscription has many VMs ( about 205) and many more resources within.
The smaller subscriptions have been opening with no problems.
The error below, also I will send an e-mail to your support and attach the log.
Thank you.
----------------------------------------------------------------------------------------
4/13/2017 10:31:25 AM   GetAzuereAsmResources  Start
4/13/2017 10:31:25 AM   GetAzureASMResources  315c3ead-44fe-4015-b353-95cfcaa09849 Start REST Request
4/13/2017 10:31:25 AM   GetAzureASMResources  315c3ead-44fe-4015-b353-95cfcaa09849 Url: https://management.core.windows.net/ba4d0106-1d2f-4416-81b3-616655127c5e/services/hostedservices/ST-DOWNLOAD04?embed-detail=true
4/13/2017 10:31:25 AM   GetAzureASMResources  315c3ead-44fe-4015-b353-95cfcaa09849 Adding authorization header: Bearer 20iLCJ1cG4iOiJBcnR5b20uS292YWx0c292QHdvbHRlcnNrbHV3ZXIuY29tIiwidmVyIjoiMS4wIn0.hRpyX3CrlQwZGd7AyESd8YaKTE9-CTs4rl8jfjVqjnxoD1731kf5Ys2kqlH0gHTYV5wEjHKx16QYTEmEJ3AR7F1k9FtwslP0KorkjYyd3kkfCk3PEZYenFJPam-1oXWd5jvxVZnDVh8oXekmDMlVU-UPGoXrlJWsqi5yGzZwAmzhOWP3CaX9pPIrBL3zID9N3dbABb1TmgLcwqyxFYrzVgrO26y9DpUrNKD2-9o2YKUuqpkz87SOg0xcuUinFlHt26DrgI0xdEZYoptuS1pqn5LF25rFeZO8lPnthG9iNzn_K_NUnCHH4hdMQLJccatUVAIMJL-IHW-89eNUZcSpmw
4/13/2017 10:31:25 AM   GetAzureASMResources  315c3ead-44fe-4015-b353-95cfcaa09849 GET https://management.core.windows.net/ba4d0106-1d2f-4416-81b3-616655127c5e/services/hostedservices/ST-DOWNLOAD04?embed-detail=true
4/13/2017 10:31:25 AM   GetAzureASMResources  315c3ead-44fe-4015-b353-95cfcaa09849 EXCEPTION The remote server returned an error: (503) Server Unavailable.
4/13/2017 10:31:25 AM   UnhandledExceptionDialog  <Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>TooManyRequests</Code><Message>Too many requests received. Retry after some time.</Message></Error>

The remote server returned an error: (503) Server Unavailable.

   at MigAz.Azure.AzureRetriever.<GetAzureAsmResources>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureAsmCloudServices>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.UserControls.Migrators.AsmToArm.<_AzureContextSourceASM_AfterAzureSubscriptionChange>d__18.MoveNext()

**Comment by PauloRamosGit** [comment]
Hi @artemaes , thank you for reporting this issue. We will look at it and get back to you.

**Comment by rsanderson2350** [comment]
@artemaes ASM To ARM Version 2.1.0.0 is awaiting merge and should be available within the next 12 hours.  I have added retry logic including a back off timer (i.e. each retry will wait progressively longer) for all 500 HTTP Errors on the REST API Calls.  Please advise if you observe the retries with the back off timer execute, as well as if it helps overcome the "Too many requests received" error you encountered.

**Comment by artemaes** [comment]
Unfortunately the issue is still in place. Please see the log below.
The app just hangs on some step and try to get the resources again and again.

4/21/2017 8:55:09 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Start REST Request
4/21/2017 8:55:09 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Url: https://management.core.windows.net/20d52582-3ffc-4e71-a175-6d3b672072cd/services/hostedservices/cognoweb?embed-detail=true
4/21/2017 8:55:09 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Adding authorization header: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzUU4wQlpTN3M0bk4tQmRyamJGMFlfTGRNTSIsImtpZCI6ImEzUU4wQlpTN3M0bk4tQmRyamJGMFlfTGRNTSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC84YWM3NmM5MS1lN2YxLTQxZmYtYTg5Yy0zNTUzYjJkYTJjMTcvIiwiaWF0IjoxNDkyNzg2MTE2LCJuYmYiOjE0OTI3ODYxMTYsImV4cCI6MTQ5Mjc5MDAxNiwiYWNyIjoiMSIsImFpbyI6IlkyWmdZUGpwcVBBOVpFdEpwRmpqSGYxblNhdU5MVDhxWHkrV21aTmF0WjFGNEhwOHhSb0EiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiMTk1MGEyNTgtMjI3Yi00ZTMxLWE5Y2YtNzE3NDk1OTQ1ZmMyIiwiYXBwaWRhY3IiOiIwIiwiZV9leHAiOjI2MjgwMCwiZmFtaWx5X25hbWUiOiJLb3ZhbHRzb3YiLCJnaXZlbl9uYW1lIjoiQXJ0eW9tIiwiZ3JvdXBzIjpbIjdiM2I1MDc3LTVhYzctNDU5Mi05NThmLTg2MWI1OTk1MmVjMiIsIjJiYTEwYjFjLTZlNjAtNDNiMy1hODBlLWM2ZjcyY2RlZmViNiIsIjIyYmQ1M2FiLTljODctNGI2Zi1hNWRkLTU4NmZiZGUyYzgwZiIsImQxODE5ZTg0LWZmYWQtNDY4Mi1hOTgxLWU2ZmMzNTBiYWU0MSIsIjRmODc1NzEwLTRkNTAtNGVlZS1hYzA4LTk0N2NiNjM1Y2QwYSJdLCJpcGFkZHIiOiI5MS4xODUuMjUuMTk0IiwibmFtZSI6IktvdmFsdHNvdiwgQXJ0eW9tIiwib2lkIjoiMjhkNDk0NDgtYjMxZC00YjEwLWE1ODgtYWQ2M2E4YzU1ZmJlIiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTcwMjA3NDE4OC0yODMzNzMyOTA3LTI0MTk1OTExNy0yNjkzMzMiLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwMzAwMDBBMEFGNDUzMiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IjFUbEdsMXBBcVNHRERqY3RqNzRmUkJTZXRVQnhQUXVWcUZ1NEhvbjdkbXMiLCJ0aWQiOiI4YWM3NmM5MS1lN2YxLTQxZmYtYTg5Yy0zNTUzYjJkYTJjMTciLCJ1bmlxdWVfbmFtZSI6IkFydHlvbS5Lb3ZhbHRzb3ZAd29sdGVyc2tsdXdlci5jb20iLCJ1cG4iOiJBcnR5b20uS292YWx0c292QHdvbHRlcnNrbHV3ZXIuY29tIiwidmVyIjoiMS4wIn0.Heq3eoUd2-Yt2RGfkyI1MkeXAlfF-mqnehh3DUQknWM3GsvLdTRJyRuf7xUUJS2sb49NaZITz-nmQ1ha457R01_1Tz-O6rOxw6O38d7flHnxwb1m_KnhxyVqvdGUbag9Hvr9TfgqxjlrQWBjQxV4j2qtiRbPuQG6z5CE39epJRwv2u8171LMtQOPZcLHAFiwpENPXJqLrc8rRZ46mW1FHNyCeK_Nsa4Zu_6TsxinhZaGtKPcL7Mut83jUrl64GhtUzo1ZwQuvGzHDbSLGI52ZQZXwU0G-CUP_GK8-nNm2FZ2AyOrlBx6YyFeywjtT6TlDmzeOzoiyLbvo5i5FF_YUw
4/21/2017 8:55:09 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 GET https://management.core.windows.net/20d52582-3ffc-4e71-a175-6d3b672072cd/services/hostedservices/cognoweb?embed-detail=true
4/21/2017 8:55:09 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 EXCEPTION The remote server returned an error: (503) Server Unavailable.
4/21/2017 8:55:09 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Sleeping for 1 second(s) (until 4/21/2017 8:55:10 PM) before web request retry.
4/21/2017 8:55:10 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Initiating retry of Web Request.
4/21/2017 8:55:10 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 EXCEPTION The remote server returned an error: (503) Server Unavailable.
4/21/2017 8:55:10 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Sleeping for 2 second(s) (until 4/21/2017 8:55:12 PM) before web request retry.
4/21/2017 8:55:12 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Initiating retry of Web Request.
4/21/2017 8:55:12 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 EXCEPTION The remote server returned an error: (503) Server Unavailable.
4/21/2017 8:55:12 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Sleeping for 4 second(s) (until 4/21/2017 8:55:16 PM) before web request retry.
4/21/2017 8:55:16 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Initiating retry of Web Request.
4/21/2017 8:55:16 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 EXCEPTION The remote server returned an error: (503) Server Unavailable.
4/21/2017 8:55:16 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Sleeping for 8 second(s) (until 4/21/2017 8:55:24 PM) before web request retry.
4/21/2017 8:55:24 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Initiating retry of Web Request.
4/21/2017 8:55:24 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 EXCEPTION The remote server returned an error: (503) Server Unavailable.
4/21/2017 8:55:24 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Sleeping for 16 second(s) (until 4/21/2017 8:55:40 PM) before web request retry.
4/21/2017 8:55:40 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Initiating retry of Web Request.
4/21/2017 8:55:40 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 EXCEPTION The remote server returned an error: (503) Server Unavailable.
4/21/2017 8:55:40 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Sleeping for 32 second(s) (until 4/21/2017 8:56:12 PM) before web request retry.
4/21/2017 8:56:12 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Initiating retry of Web Request.
4/21/2017 8:56:12 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 EXCEPTION The remote server returned an error: (503) Server Unavailable.
4/21/2017 8:56:12 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Sleeping for 64 second(s) (until 4/21/2017 8:57:16 PM) before web request retry.
4/21/2017 8:57:16 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Initiating retry of Web Request.
4/21/2017 8:57:16 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 EXCEPTION The remote server returned an error: (503) Server Unavailable.
4/21/2017 8:57:16 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Sleeping for 128 second(s) (until 4/21/2017 8:59:24 PM) before web request retry.
4/21/2017 8:59:24 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Initiating retry of Web Request.
4/21/2017 8:59:24 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 EXCEPTION The remote server returned an error: (503) Server Unavailable.
4/21/2017 8:59:24 PM   GetAzureASMResources  3b5ef1e8-e689-4340-8bdd-946a6ff725f8 Sleeping for 256 second(s) (until 4/21/2017 9:03:40 PM) before web request retry.

**Comment by artemaes** [comment]
I found an article about the error. Please take a look.
гипотетически может быть с этим связано
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits

**Comment by PauloRamosGit** [comment]
Thank you @artemaes . we will include the link on the documentation
