### ISSUE TITLE
MigAz AWS (1.0.0.3) VM export fails on specific Security Groups

### ISSUE THREAD

**Issue by bswedeen** [Azure/migAz#29]
Exporting EC2 instances for a specific AWS VPC hangs when it hits a certain Security Group. 

"Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index"

I resolved this issue by editing the problematic Security Group and removing the ICMP traffic rules. Re-run after that was successful.

A similar error occurred running against a different VPC with different Security Groups.  Similarity between the two SGs is that both had restrictive ICMP rules.  The full details of the error message are attached in a text file.
[errormessagedetails.txt](https://github.com/Azure/migAz/files/942697/errormessagedetails.txt)

**Comment by PauloRamosGit** [comment]
Thank you @bswedeen for reporting and detail explanation. I will try to repo the problem and get back to you.

**Comment by PauloRamosGit** [comment]
Thank you @bswedeen for confirming that the issue is solved on the upcoming v1.0.0.4
