### ISSUE TITLE
MigAz AWS (1.0.0.3) Not Respecting Unique Suffix

### ISSUE THREAD

**Issue by bswedeen** [Azure/migAz#30]
Setting a unique suffix in the options menu fails to add the unique identifier to the file name.  Each run of the tool keeps outputting export.json and overwriting the previous run.  Temporary work around: Make unique directories and point each run to a different directory.

**Comment by PauloRamosGit** [comment]
Hi @bswedeen , the unique suffix is used on the storage account names and dns names only. They are not used on the output template file name.
For each export you should use a different directory.
Do you think it would be helpful to also allow to state the file name is the path?

**Comment by bswedeen** [comment]
Thanks for the correction/explanation.  As for including a file name in the path...I suppose it would be nice, but I don't think it's critical.  I think it would be better to provide a little context around the "unique suffix."  Maybe extend the dialog box description to say "storage account unique suffix."

**Comment by PauloRamosGit** [comment]
Thanks for the feedback. We will look into include it soon.
