### ISSUE TITLE
Incorrect subscription ID in export file

### ISSUE THREAD

**Issue by JoshAFraser** [Azure/migAz#31]
Hi, 

I'm currently using MigAz to create some ASM to ARM migrations and one thing I noticed is that the 'Target Subscription' ID is incorrect when you export the file.  Its actually using the source subscription ID!

**Comment by rsanderson2350** [comment]
@JoshAFraser Thanks Josh, I'll check this out and get it in the next revision.  There were some recent code changes in that section, so it must be using the Source context, not the Target context.  Thank you.

**Comment by JoshAFraser** [comment]
@rsanderson2350 No problem! once I ran the process a second time and changed the subscriptionID things went well!
