### ISSUE TITLE
export.json template is not getting update when changes are made in options like use existing ARM vnet, ARM storage account

### ISSUE THREAD

**Issue by adityakumar60** [Azure/migAz#32]
export.json template is not getting updated when changes are made in options like when I select option use existing ARM vnet and subnet , ARM storage account etc

**Comment by PauloRamosGit** [comment]
Hi @adityakumar60 , we will take a look and get back to you.

**Comment by rsanderson2350** [comment]
@adityakumar60  Can you provider further details including what version you are using, as well as steps to reproduce including what is not being updated?  The export.json file is not rewritten every time you make a property change.  You do need to click the Export button at the bottom right of the form to re-generate the export.json file after changing various properties.

**Comment by adityakumar60** [comment]
Hi,

I am using the MigAz v2.1.0.0, when I change the properties like storage
account, disk name etc for target and then click on the export button, the
changes are not being reflected into the export.json template.

It works fine in MigAz v1.5 but not sure why it is not working in MigAz
v2.1.0.0.

Also, I want to know if my machines(ASM and ARM) are joined in same AD
domain, after migration which one will be resolved by AD, since both the
machines have same host name.

**Comment by rsanderson2350** [comment]
@adityakumar60 We will be releasing the next version this weekend, which is going to introduce ARM exporting as well in the same build.  I'll double check all of the property dialogs in comparison to the template generation.  

Regarding your question about ASM vs. ARM copies of the VMs, it is important to note that this process is facilitating migration from ASM to ARM by way of copying the VM disk(s).  As you noted, the VM may be domain joined to either an IaaS Domain or to an Azure AD Domain.  You should power down your ASM Virtual Machine, perform the MigAz migration (copy) and then power on your ARM Virtual Machine deployment.  Validate the ARM migration.  If valid, you should now continue forward with the ARM version of your VM being your official/master VM that is online and operational.  You are correct and you do not want multiple "cloned" copies of a domain joined machine contending against each other.

**Comment by adityakumar60** [comment]
Hi,

Have you released the new version ?

Also, could you please let me know what changes are required in the
export.json template to convert the VHD's into managed disks?

Thanks,
Aditya

**Comment by PauloRamosGit** [comment]
Hi @adityakumar60 , until we fully support managed disks on migAz use https://docs.microsoft.com/en-us/azure/virtual-machines/windows/migrate-to-managed-disks to make this conversion.
