### ISSUE TITLE
Source ASM window not showing all resources

### ISSUE THREAD

**Issue by evanaross** [Azure/migAz#35]
The display window for resources does not show all resources.  The scroll bar is there, but I can not see the bottom of the tree view window.

**Comment by PauloRamosGit** [comment]
Hi @evanaross , can you send us a screenshot to support@migaz.tools?

**Comment by rsanderson2350** [comment]
@evanaross I did observe scroll bar issues and have done changed in the next release that should have this issue resolved.  This next release merges with both ASM and ARM resources and I need to finish that up.  I'll post an update here when we merge the next update for release (possibly a day or two), but we'll try to get that posted ASAP for you to use.

**Comment by adityakumar60** [comment]
We are also facing same issue, When can we expect the updated release, I would request you to please release it asap. we have a planned activity this weekend.

**Comment by rsanderson2350** [comment]
Release of the next version is anticipated in approximately 12 hours.

**Comment by rsanderson2350** [comment]
I need to finish up code changes on ASM to ARM Network Interfaces, VNet/Subnet and copyblob.json outputs in the morning tomorrow before it is stable for a new release, given some of the major code transformations.  I've compiled a preview of the next release.  Fell free to preview it, but again note that I need to work on it a bit more tomorrow morning.

https://github.com/rsanderson2350/migAz/blob/master/Release/MigAz%20v2.1.9.9.zip

**Comment by adityakumar60** [comment]
Hi,

Thanks for the update, as i cant see the latest release in repo, please let
me know if it will take some more time.

Regards,
Aditya Kumar

**Comment by rsanderson2350** [comment]
2.2.0.0 build compiled https://github.com/rsanderson2350/migAz/blob/master/Release/MigAz%20v2.2.0.0.zip  Awaiting pull request merge.

**Comment by rsanderson2350** [comment]
A newer release is now available.  Please advise of any issues you observe with the updated release.  Thanks.

**Comment by adityakumar60** [comment]
Hi,

I have noticed below issues:

1. The availability set names are wrong, it just keep the cloud service
name as availability set name not the actual one.
2. When I deselect the load balancer and only select the VM. but there are
still loadBalancerBackendAddressPools and loadBalancerInboundNatRules
configuration/rules exists.
