### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by PauloRamosGit** [Azure/migAz#37]
Hi @evamshi, this is your new issue entry. We will look at it and get back to you.

Object reference not set to an instance of an object. at MigAz.Azure.AzureRetriever.<GetAzureAsmResources>d__32.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at MigAz.Azure.AzureRetriever.<GetAzureAsmVirtualNetworks>d__37.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at MigAz.UserControls.Migrators.AsmToArm.<_AzureContextSourceASM_AfterAzureSubscriptionChange>d__18.MoveNext()

**Comment by PauloRamosGit** [comment]
Hi @evamshi, can you please check if the problem is solved with the new 2.2.1.0?

**Comment by rsanderson2350** [comment]
A newer release is now available.  Please advise of any issues you observe with the updated release.  Thanks.

**Comment by PauloRamosGit** [comment]
Solved
