### ISSUE TITLE
Region update 

### ISSUE THREAD

**Issue by madhavi-m** [Azure/migAz#44]
Bug: When selecting a region in the next steps dialog of MigAZ -ARM tool, and click ok. The template file is not updated with the new region selected, instead contains the old region and hence creates the resources in old region.

**Comment by rsanderson2350** [comment]
Thanks @madhavi-m .   I think I'm going to change all location references to simply consume from the parent (owning) resource group object, rather than having to reference a specific location target for new resources.  Thanks for the feedback and bug alert.  I'll post an update shortly.

**Comment by rsanderson2350** [comment]
@madhavi-m A newer release is now available.  Please advise of any issues you observe with the updated release.  This issue should be resolved.  Thanks.

**Comment by PauloRamosGit** [comment]
Solved
