### ISSUE TITLE
Version V2.2.1.0 issues

### ISSUE THREAD

**Issue by adityakumar60** [Azure/migAz#45]
Sorry to say but new release has lots of issues.

1. It gives wrong availability set names in templates
2. Does not create dependencies as well like load balancers for cloud service.
3. It give an error virtual network does not found, if we use existing VNet while deploying the template

Request you to please look into it.

**Comment by rsanderson2350** [comment]
@adityakumar60 A newer release is now available.  Please advise of any issues you observe with the updated release.  Thanks.

**Comment by adityakumar60** [comment]
Hi,

I have noticed below issues:

1. The availability set names are wrong, it just keep the cloud service
name as availability set name not the actual one.
2. When I deselect the load balancer and only select the VM. but there are
still loadBalancerBackendAddressPools and loadBalancerInboundNatRules
configuration/rules exists.
