### ISSUE TITLE
403 forbidden when initiating up any kind of migration

### ISSUE THREAD

**Issue by prestifare** [Azure/migAz#47]
Using v.2.2.3.0 and AzureCloud.

Two subscriptions - both in same tenant. One is CSP, other is a freebie using credits. After signing in and selecting any of the subscriptions, application throws the following error:

<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

The remote server returned an error: (403) Forbidden.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureAsmResources>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureAsmNetworkSecurityGroups>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.UserControls.Migrators.AsmToArm.<_AzureContextSourceASM_AfterAzureSubscriptionChange>d__29.MoveNext()

User account is owner of both subscriptions.

Any help appreciated.

**Comment by rsanderson2350** [comment]
@prestifare If you look at the Log tab at the bottom, and locate the 403 Forbidden Error towards the bottom, what is the URL just before the error?  You should see a line that looks like:

DateTimeHere **GetAzureRestResponse**  RequestGuidHere Url: **https://.......**

**Comment by prestifare** [comment]
@rsanderson2350 Not entirely sure what identifies my stuff and not, so substed all GUID-like entries:

22.05.2017 20.52.15   GetToken  Start token request
22.05.2017 20.52.15   GetToken  Azure Subscription: SubstSubscrName (#####-####-####-####-##########)
22.05.2017 20.52.15   GetToken  Authentication Url: https://login.microsoftonline.com/#####-####-####-####-##########
22.05.2017 20.52.15   GetToken  End token request
22.05.2017 20.52.15   GetAzureAsmNetworkSecurityGroups  Start
22.05.2017 20.52.15   GetAzuereAsmResources  Start
22.05.2017 20.52.15   GetAzureASMResources  Start REST Request
22.05.2017 20.52.15   GetAzureRestResponse  #####-####-####-####-########## Url: https://management.core.windows.net/#####-####-####-####-##########/services/networking/networksecuritygroups
22.05.2017 20.52.15   GetAzureRestResponse  #####-####-####-####-########## GET https://management.core.windows.net/#####-####-####-####-##########/services/networking/networksecuritygroups
22.05.2017 20.52.15   cmbSubscriptions_SelectedIndexChanged  End
22.05.2017 20.52.16   GetAzureRestResponse  #####-####-####-####-########## EXCEPTION The remote server returned an error: (403) Forbidden.
22.05.2017 20.52.16   GetAzureRestResponse  #####-####-####-####-##########  EXCEPTION The remote server returned an error: (403) Forbidden.
22.05.2017 20.52.16   UnhandledExceptionDialog  <Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

The remote server returned an error: (403) Forbidden.

**Comment by rsanderson2350** [comment]
@prestifare The call to getting ASM based Network Security Groups is the first REST call after selecting a subscription context.  You have clearly passed authentication and obtained a list of the Tenant(s) and Subscription(s); however, upon selecting a subscription the first call to retrieve objects is not authorized.  Have you been able to verify the same account does in fact have the necessary permission grants (i.e. can you get a list of ASM Network Security Groups back in PowerShell or CLI) with that account authenticated?  I have tried the 3 Azure AD accounts I have access to across 2 different Azure Environments, and all authenticate and successfully retrieve the objects.  

@PauloRamosGit Have you seen 403 Forbidden issues historically? Any other recommendations besides reviewing the account permissions?

**Comment by rsanderson2350** [comment]
@prestifare Also to confirm, is this occurring under the following order of operation:  1) Launch MigAz program; 2) Start new Migration; 3) Click Change button; 4) Authenticate; 5) Select Tenant/Subscription?  Or is there any other variation to this order of operation that you are performing, such as signing out from an existing authentication and changing to another account?

**Comment by prestifare** [comment]
@rsanderson2350  That is roughly the sequence, yes. However (at least in the version I'm using) starting a new migration automatically triggers authentication, so it's more like 1) Launch MigAz; 2) File -> New Migration -> whateveroption (they all produce the same error); 3) Authenticate; 4) Select tenant/subscription.

As soon as I select one of my two subscriptions, the 403 error appears. Same thing happens when clicking "Change" at any time afterwards.

A couple of things I've noticed that might be important:

* After signing in and populating the tenant field (I have only one), the status bar at the bottom is stuck on "BUSY: Getting subscriptions". I am however able to select subscriptions from the dropdown, and no errors are logged.

* Both subscriptions are ARM, which might explain why ASM NSG fails (albeit not why it gives a 403)?

**Comment by rsanderson2350** [comment]
@prestifare If you try the last stand alone version of the ARM to ARM only tool, what result do you get when authenticating?  https://github.com/Azure/migAz/blob/bbfd73f1e2106178f05506f593111c005993eba2/arm/release/migAz%20ARM%20v1.0.0.1.zip

**Comment by prestifare** [comment]
@rsanderson2350 Found the issue. The account used was not co-admin in the subscription that contains classic/ASM resources. I figured "owner" would be sufficient, but apparently not. Everything works now, thanks for your assistance.

**Comment by rsanderson2350** [comment]
@prestifare Ok, thanks for the feedback.  I think for a future release I'm going to separate the ASM and ARM loading logic, as well as wrap each with separated try/catch logic.  Glad to hear you have it operational.

**Comment by rsanderson2350** [comment]
Version 2.2.4.0 is awaiting PR and will be available as soon the PR is processed, and this should be handled as of 2.2.4.0

**Comment by rsanderson2350** [comment]
Should be handled better with v2.2.6.0, per UI separation of ASM vs ARM.

**Comment by prestifare** [comment]
@rsanderson2350 Tried to re-run same workload as stated above with 2.2.6.0.

Flow is: Migration/New migration -> Azure ASM to ARM - > Sign in and choose "ASM" subscription.

migAz now populates "Source ASM resources" properly, but stops some way through (seems to hang on GetAzureAsmReservedIPs):

07.06.2017 09.23.59   GetAzuereAsmResources  Start
07.06.2017 09.23.59   GetAzureASMResources  Start REST Request
07.06.2017 09.23.59   GetAzureRestResponse  00941273-ce26-4bb9-8203-dbd2e325e798 Url: https://management.core.windows.net/160aa1b9-e9f9-46fe-b1f1-3004b5b6217e/services/hostedservices/hrgwgcsimduat01?embed-detail=true
07.06.2017 09.23.59   GetAzureRestResponse  00941273-ce26-4bb9-8203-dbd2e325e798 Using Cached Response
07.06.2017 09.23.59   GetAzureRestResponse  00941273-ce26-4bb9-8203-dbd2e325e798 End REST Request
07.06.2017 09.23.59   GetAzuereAsmResources  Start
07.06.2017 09.23.59   GetAzureASMResources  Start REST Request
07.06.2017 09.23.59   GetAzureRestResponse  4e307ea7-a5f9-4ee0-832b-3bff7e03da6d Url: https://management.core.windows.net/160aa1b9-e9f9-46fe-b1f1-3004b5b6217e/services/hostedservices/hrgwgcsimduat01/deployments/hrgwgcsimduat01/roles/hrgwgcsimduat01
07.06.2017 09.23.59   GetAzureRestResponse  4e307ea7-a5f9-4ee0-832b-3bff7e03da6d GET https://management.core.windows.net/******/services/hostedservices******/deployments/******/roles/*****
07.06.2017 09.23.59   GetAzureRestResponse  51e897cf-fe73-41b3-8157-65802d9636cc Received REST Response
07.06.2017 09.23.59   GetAzureRestResponse  51e897cf-fe73-41b3-8157-65802d9636cc Received REST Response
07.06.2017 09.23.59   GetAzureRestResponse  51e897cf-fe73-41b3-8157-65802d9636cc  Status Code OK
07.06.2017 09.23.59   GetAzureRestResponse  51e897cf-fe73-41b3-8157-65802d9636cc End REST Request
07.06.2017 09.23.59   GetAzureAsmStorageAccount  Start
07.06.2017 09.23.59   GetAzureAsmStorageAccounts  Start
07.06.2017 09.23.59   GetAzureAsmReservedIPs  Start
07.06.2017 09.24.00   GetAzureRestResponse  140b083d-5265-4df8-8bce-7428259a69b8 Received REST Response
07.06.2017 09.24.00   GetAzureRestResponse  140b083d-5265-4df8-8bce-7428259a69b8 Received REST Response
07.06.2017 09.24.00   GetAzureRestResponse  140b083d-5265-4df8-8bce-7428259a69b8  Status Code OK
07.06.2017 09.24.00   GetAzureRestResponse  140b083d-5265-4df8-8bce-7428259a69b8 End REST Request
07.06.2017 09.24.00   GetAzureAsmStorageAccount  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccounts  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccount  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccounts  Start
07.06.2017 09.24.00   GetAzureAsmReservedIPs  Start
07.06.2017 09.24.00   GetAzureRestResponse  4e307ea7-a5f9-4ee0-832b-3bff7e03da6d Received REST Response
07.06.2017 09.24.00   GetAzureRestResponse  4e307ea7-a5f9-4ee0-832b-3bff7e03da6d Received REST Response
07.06.2017 09.24.00   GetAzureRestResponse  4e307ea7-a5f9-4ee0-832b-3bff7e03da6d  Status Code OK
07.06.2017 09.24.00   GetAzureRestResponse  4e307ea7-a5f9-4ee0-832b-3bff7e03da6d End REST Request
07.06.2017 09.24.00   GetAzureAsmStorageAccount  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccounts  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccount  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccounts  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccount  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccounts  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccount  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccounts  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccount  Start
07.06.2017 09.24.00   GetAzureAsmStorageAccounts  Start
07.06.2017 09.24.00   GetAzureAsmReservedIPs  Start

And it just sits there indefinitely..

Furthermore, trying to change "Azure ARM (Target Subscription)" (it defaults to the same subscription as source, would be nice to be able to select both when defining migration) just hangs on "BUSY: Getting subscriptions".

**Comment by prestifare** [comment]
Appears to be resolved in 2.2.9.0, thanks.

**Comment by PauloRamosGit** [comment]
Solved
