### ISSUE TITLE
Discard error messages

### ISSUE THREAD

**Issue by danielurbina** [Azure/migAz#50]
Hi. This is a great tool. Please keep up the good work.
I'm trying to use it to replicate environments and I'm struggling with the problem that migAz finds out that I'm moving a VM without an availability set and it won't allow me to do this unless I select Premium Disk (which I haven't found a wa to do from the UI).
I think there should be a way to discard the very useful information that it's provided. Some sort of checkbox (in the option menú) saying "I know I cannot claim SLA for this deployment".
Thank you and as said: keep up the great work.
Regards

**Comment by rsanderson2350** [comment]
I have lowered this to be just a warning (that will allow you to proceed) until another future update in which we can add better manageability of these settings.  Version 2.2.4.0 is awaiting PR and will be available as soon the PR is completed.

**Comment by rsanderson2350** [comment]
Recommend issue closure, as this is a soft warning, and v2.2.7.0 added the ability to change the storage account type via dropdown selection.

**Comment by danielurbina** [comment]
I totally agree. Thank you very much for your work.
