### ISSUE TITLE
Error after sign in

### ISSUE THREAD

**Issue by gszeifert** [Azure/migAz#55]
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

A távoli kiszolgáló a következő hibát küldte vissza: (403) Tiltott.

   a következő helyen: MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__81.MoveNext()
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   a következő helyen: MigAz.Azure.AzureRetriever.<GetAzureAsmResources>d__79.MoveNext()
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a következő helyen: MigAz.Azure.AzureRetriever.<GetAzureAsmNetworkSecurityGroups>d__44.MoveNext()
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by rsanderson2350** [comment]
Should be handled better with v2.2.6.0, per UI separation of ASM vs ARM.

**Comment by gszeifert** [comment]
Thanks seems to be ok!
