### ISSUE TITLE
ASM CloudService loadbalancer http probe request path error

### ISSUE THREAD

**Issue by The-TeQnician** [Azure/migAz#60]
Hi, 

While testing MigAz i noticed the following error. Here i am migrating 2 ASM VM's with a cloud service and a load balancer with probes on tcp poort 80.

===================================================================

New-AzureRmResourceGroupDeployment : 14:13:25 - Error: Code=InvalidTemplateDeployment; Message=The template deployment 'export' is not valid according to the validation procedure. 
The tracking id is '65c53019-f24b-4923-a3a0-f2cc35f86546'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName "BVGO-RSG-Cloud ...
+ CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
New-AzureRmResourceGroupDeployment : 14:13:25 - Error: Code=ProbeRequestPathIsNotNull; Message=Request path for probe 
/subscriptions/4bdf9eb4-115a-4108-8805-a0103d5c16e9/resourceGroups/BVGO-RSG-Cloudapp/providers/Microsoft.Network/loadBalancers/armvmtest2/probes/cloudapp-site must be null when its protocol is Tcp.
At line:1 char:1
====================================================================
Turns out that the output of the MigAz tool is also creating a line for an http probe request path without a value

==========
        "probes": [
          {
            "name": "cloudapp-site",
            "properties": {
              "protocol": "tcp",
              "port": 80,
              "intervalInSeconds": 15,
              "numberOfProbes": 2,
              "requestPath": ""
            }
          }
        ]
==========
When i removed the "RequestPath": "" part from the export.json the deployment was running fine, so it seems like the line should not be there when a tcp probe is used instead of an http probe?

**Comment by The-TeQnician** [comment]
Sorry about the layout took me 10 minutes to try and get it right but i gave up :(

**Comment by rsanderson2350** [comment]
Awaiting pull of v2.2.9.0.  RequestPath should no longer output as of v2.2.9.0 if it is an empty string.

**Comment by PauloRamosGit** [comment]
Solved

**Comment by gituser2291** [comment]
@The-TeQnician @PauloRamosGit  I am encountering same issue where it states 'must be null when its protocol is Tcp (Code: ProbeRequestPathIsNotNull).  What was the resolution to this?

**Comment by ruandersMSFT** [comment]
@gituser2291 Try removing the requestPath parameter so that it is not present from your generated ARM Template and run it again.
