### ISSUE TITLE
Reserved IP

### ISSUE THREAD

**Issue by zimbonz** [Azure/migAz#63]
Hi, 
I have a reserved IP applied to a classic cloud service. When i use the tool to scan, it picks up a PIP from the source subscription, but the public IP that is created in the ARM subscription is not the same.
Even selecting static as the PIP type, by editing the export.json will produce a random IP.
Is there anyway to migrate the reserved IP with migaz, or any recommended procedure?
Thanks,
Zim

**Comment by PauloRamosGit** [comment]
Hi @zimbonz , migAz creates an ARM template to redeploy the resources. ARM does not allow (at least yet) for you to specify the Public IP address you want to use.
The only way to migrate the resources and keep the same reserved Public IP address is using the platform native migration (https://docs.microsoft.com/en-us/azure/virtual-machines/windows/migration-classic-resource-manager-deep-dive).
