### ISSUE TITLE
"Plan" section on ARM VMs not exported

### ISSUE THREAD

**Issue by MAPMA** [Azure/migAz#67]
The "Plan" section on the VMs is not exported to JSON (On VMs that have it obviously).
If I download the automation script from the Portal UI the section is there.

**Comment by rsanderson2350** [comment]
Plan attributes have been added into the next release, as I've been working with similar marketplace items that require the "plan" attributes as part of their deployment.  Would appreciate your confirmation of issue resolution upon v 2.2.11.0 or later.

**Comment by MAPMA** [comment]
Hi,
 Just used v 2.2.11.0 and can confirm the "plan" section & properties was exported correctly.

Thanks.
Marco

**Comment by rsanderson2350** [comment]
@MAPMA Thanks for verifying.

**Comment by PauloRamosGit** [comment]
Solved
