### ISSUE TITLE
ASM resources are not loading on MIgAz

### ISSUE THREAD

**Issue by gguimaraes184** [Azure/migAz#69]
Hi all,

I'm getting the error below when I sign in with azure account on MigAz.

<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

O servidor remoto retornou um erro: (403) Proibido.

   em MigAz.Azure.AzureRetriever.<GetAzureAsmResources>d__32.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em MigAz.Azure.AzureRetriever.<GetAzureAsmVirtualNetworks>d__37.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em MigAz.UserControls.Migrators.AsmToArm.<_AzureContextSourceASM_AfterAzureSubscriptionChange>d__18.MoveNext()

I've tried with another account and works fine.

Does somebody knows what issue is it?

Thanks,

**Comment by rsanderson2350** [comment]
@gguimaraes184 See issue #47 .  

The reported resolution for 403 Forbidden against an ASM/Classic Azure Subscription was that the account being used is not a co-admin on the subscription ("owner" access was not sufficient).

**Comment by gguimaraes184** [comment]
Thanks so much rsanderson2350.  

Is there any way to create more than one admin on Azure? I mean not co-admin.

**Comment by rsanderson2350** [comment]
I would recommend reviewing the following article:

https://azure.microsoft.com/en-us/support/changing-service-admin-and-co-admin/

The primary breakdown here is that there are the service (primary) admin accounts that are defined with the subscription, but you can then add other co-admins.  You should look to add other account(s) (specifically, the account you are wanting to use with MigAz) as a co-admin within the subscription.

**Comment by rsanderson2350** [comment]
Here's another resource:

https://docs.microsoft.com/en-us/azure/billing/billing-add-change-azure-subscription-administrator

See the "Azure classic portal" section

**Comment by gguimaraes184** [comment]
Thanks @rsanderson2350.  I would like to create more than one service admin but is not possible, Anyway, I'm very gratefull for your help. I'll change the service admin and try to login again on migaz.

**Comment by PauloRamosGit** [comment]
Solved
