### ISSUE TITLE
MigAz v2.2.11.0 - New static IP is not written in export.json template

### ISSUE THREAD

**Issue by KamilSzafarczyk** [Azure/migAz#70]
Hi,
The new static IP is not written in export.json template when using migtate to existing arm vnet in tartget option

![capture](https://user-images.githubusercontent.com/26961275/27637926-c1e3ac16-5c11-11e7-9c5c-1cb5aa9336db.JPG)

**Comment by rsanderson2350** [comment]
Identified a object properties that overlapped in scope, resolved.  Issue should be resolved in current version 2.2.12.0.
