### ISSUE TITLE
Azure mART Tool

### ISSUE THREAD

**Issue by nexxt66** [Azure/migAz#71]
Hi Paulo,

I'm unsure if you wrote the Excel Tool mART for checking service availability in ARM from an EA consumption sheet, but i'd like to report an error and to, if possible, request some assitance in fixing it.

Tool stops on line 
    Range("DetailedUsage[[#Headers],[Column1]]").Select

appreciate any help regarding this.

thanks!

**Comment by PauloRamosGit** [comment]
Closing the issue since not related with migAz
