### ISSUE TITLE
MigAz - ASM to ARM 

### ISSUE THREAD

**Issue by kirubakaranja** [Azure/migAz#73]
while connect azure Account am getting below msg:
![capture](https://user-images.githubusercontent.com/30107829/28107805-e94bc266-6706-11e7-9590-206f9ff37710.JPG)

The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>
The remote server returned an error: (403) Forbidden.

**Comment by katomel4** [comment]
same with me

**Comment by rsanderson2350** [comment]
See issue #69 and #47.  

Ensure the account you are using has been granted co-administrator access to your Azure Subscription in the Azure Classic Portal.

https://docs.microsoft.com/en-us/azure/billing/billing-add-change-azure-subscription-administrator

See the "Azure classic portal" section.

**Comment by rsanderson2350** [comment]
The latest version, v2.2.12.0, has been updated with an ASM 403 Forbidden custom error dialog to help guide the user to the above referenced link to aid in configuring the Classic ASM subscription co administration permission.
