### ISSUE TITLE
ASM to ARM: No resources in "Source ASM Resources" window

### ISSUE THREAD

**Issue by SaadKhamis** [Azure/migAz#75]
[Log 2017-07-26.txt](https://github.com/Azure/migAz/files/1178187/Log.2017-07-26.txt)

Please review the attached log file. I'm a "Global Administrator".

**Comment by rsanderson2350** [comment]
Referencing issue #47, #62 and #69, an account does need to be granted co-administrator permission.  A "global administrator" / "owner" account differs from co-administrator access in classic ASM and doesn't have the necessary permissions to iterate the ASM object details.  

https://azure.microsoft.com/en-us/support/changing-service-admin-and-co-admin/
https://docs.microsoft.com/en-us/azure/billing/billing-add-change-azure-subscription-administrator

**Comment by SaadKhamis** [comment]
Thank you.
