### ISSUE TITLE
Unable to connect to Azure ASM resources after migrating VM to ARM

### ISSUE THREAD

**Issue by garnain** [Azure/migAz#80]
Hello, hoping someone can help. I have successfully migrated a classic VM to ARM in Azure using MigAZ however I am now unable to access any of the existing ASM resources. The VM is connected to the ASM Vnet which I think might be the problem but I understand it is not possible to change the VNet in ARM. Please help! thanks

**Comment by wrapmaster4500** [comment]
When you migrate from ASM to ARM, all resources are recreated including the networks etc. ARM machines do not have access to ASM networks. You can enable this if you use VPN (peering), but obviously you would need to migrate to an alternative IP range. This would not happen by default and requires altering the json exported from MigAz. 

In short - ARM machines can only be attached to ARM resources, the can be given access to some ASM resources but that would require extra configuration, like setting up a VPN. I'm sure I worded this terribly

**Comment by garnain** [comment]
Thanks for the reply, in order to resolve this will I need to migrate again
or can I somehow change the IP range on the already migrated VM?

**Comment by MAPMA** [comment]
What do you mean "The VM is connected to the ASM Vnet"? You cannot deploy an ARM VM on an ASM VNet. Nor will MigAz allow you to migrate a VM without migrating it's VNet: "Target Virtual Network '%your vnet%' for Virtual Machine '%VM%' Network Interface '%NIC%' is invalid, as it is not included in the migration / template."

You need to consider the group of resources that need to work together when planning the migration, you cannot carry it out on a VM by VM basis.

**Comment by wrapmaster4500** [comment]
The principals of VPN would remain the same, the 2 networks would need to be different. The initial migration VNET should be removed, as it will be identical to the ASM VNET. There are templates for changing a machine network. If you've originally used 10.0.0.0/8 you'll need to go to an entirely new IP range, 192.168.0.0/22 should give you plenty to work with.

Probably at this point it would be easier to create a new ARM VNET and set up the VPN (and DNS)
You could delete the machine, but not the disks and then run a template that is for an existing disk and existing vnet, such as https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-specialized-vhd-existing-vnet. 

Or remove the entire initial migration and then alter the template before deploying it again via MigAz. 
Aidan finn put together a decent walkthrough on the use of MigAz - http://www.aidanfinn.com/?p=19762 , it also shows how to alter the template and explains setting up a VPN to link new and old. Obviously take only what you need IIRC his describes syncing SQL etc.

**Comment by MAPMA** [comment]
What do you mean "The VM is connected to the ASM Vnet"? You cannot deploy an ARM VM on an ASM VNet. Nor will MigAz allow you to migrate a VM without migrating it's VNet: "Target Virtual Network '%your vnet%' for Virtual Machine '%VM%' Network Interface '%NIC%' is invalid, as it is not included in the migration / template."

You need to consider the group of resources that need to work together when planning the migration, you cannot carry it out on a VM by VM basis.
