### ISSUE TITLE
Cannot validate argument on parameter 'StorageAccountKey'

### ISSUE THREAD

**Issue by mwijsman76** [Azure/migAz#81]
Hi,

When running AzMig v2.2.13.0 I get the error message blow.

The storage account that is defined in the export.json is in a different resource group. When looking at the copyblobdetails.json there is no value defined for DestinationKey. Hence the error message.

Is this because the storage account is in a different resource group or could this be a bug?

Cheers
Maarten

**Error message:**
New-AzureStorageContext : Cannot validate argument on parameter 'StorageAccountKey'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At BlobCopy.ps1:93 char:133
+ ... etail.DestinationSA -StorageAccountKey $copyblobdetail.DestinationKey
+                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzureStorageContext], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageContext

**Comment by rsanderson2350** [comment]
@mwijsman76 It is an underlying bug in the tool.  I'll see if I can get a fix created soon for it.  I have encountered this before and the way I have overcome it is to provide the ResourceGroupName that your storage account is in when calling both blob copy operations (Start and Monitor operations), but then using the true target ResourceGroupName when calling the final New-AzureRmResourceGroupDeployment call to deploy export.json.

**Comment by rsanderson2350** [comment]
@mwijsman76 With version 2.2.14.0, I have moved the ResourceGroupName parameter from being a pass in parameter to the BlobCopy.ps1 command and the ResourceGroupName is now part of each blob copy entry within the copyblobdetails.json file.  This should accommodate for use of various Resource Groups, allowing for the targeting of an existing storage account (that is not in the same Resource Group).

**Comment by rsanderson2350** [comment]
Closing issue, per release of version 2.2.14.0 to address issue.
