### ISSUE TITLE
Unable to move Basic VM due to Load Balancer

### ISSUE THREAD

**Issue by elitemicro** [Azure/migAz#86]
When trying to use MigAz to migrate ASM to ARM for Basic VMs, the JSON created errors out due to load balancer creation. Would it possible to have the option to select not to create a load balancer rather than having to upgrade the machine doubling the Azure price or manually fixup the JSON? Personally I wouldn't know where to start on fixing the JSON!

New-AzureRmResourceGroupDeployment : 13:19:39 - Resource Microsoft.Compute/virtualMachines 'SV001' failed with
message '{
  "error": {
    "details": [],
    "code": "LoadBalancingNotSupportedForBasicVm",
    "message": "Load balancing is not supported for Basic VM sizes. VM SV001 has size Basic_A1 but uses network
interface SV001-NIC1 associated with load balancer backend address pool default."
  }
}'

**Comment by rsanderson2350** [comment]
Are there multiple Virtual Machines behind the Load Balancer?  Any insight into what the load balancer is "load balancing"?

**Comment by MAPMA** [comment]
@rsanderson2350 In ASM there is a load balancer implicit on every cloud service and that's how it's possible to convert the VMs to ARM mode. In ASM, if you have more than one VM on the same cloud service at the very least the load balancer is there for the NAT rules (if not for load balancing).

**Comment by rsanderson2350** [comment]
@MAPMA If you feel this is a single / standalone VM and there is no need for a load balancer, then you could delete the load balancer resource from the export.json, as well as delete any "depends on" lines that reference that load balancer name (within the VM resource or Network Interface resource).  

If you do need a load balancer to continue to perform load balancing or NAT rules, then you would need to increase the VM to Standard tier.

**Comment by MAPMA** [comment]
@rsanderson2350 I agree, there's no need (I was editing my reply). Was just clarifying why it "appears" on the JSON template when converting ASM to ARM.

**Comment by elitemicro** [comment]
Thanks, this is a standalone machine that does not require load balancing, and as it's a Basic_A1, doesn't support load balancing.

Is it simply a case of stripping out the
"type": "Microsoft.Network/loadBalancers
section?

**Comment by rsanderson2350** [comment]
yes, strip our that load balancer resource section.  Take note of the name, ensure that it is the correct load balancer (if you have more that one load balancers in the export.json).  You will also need to remove any "depends on" lines (search the export.json file again and locate any lines that reference that load balancer name that you are deleting).
