### ISSUE TITLE
InvalidTemplateDeployment

### ISSUE THREAD

**Issue by ch40sth30ry** [Azure/migAz#87]
I'm testing MigAz with a demo Azure environment where I'm attempting to migrate 2 VM's, 1 VNET and a cloud service from Classic to Resource Manager. I'm getting the following series of errors when I try to migrate ... can you help?

PS C:\> New-AzureRmResourceGroupDeployment -ResourceGroupName "ResourceGroup" -TemplateFile "c:\temp\export.json"
New-AzureRmResourceGroupDeployment : 2:50:48 PM - Error: Code=InvalidTemplateDeployment; Message=The template deployment 'export' is not valid according
to the validation procedure. The tracking id is 'a1fd185d-6167-4be6-842a-4b85020a0b9e'. See inner errors for details. Please see
https://aka.ms/arm-deploy for usage details.
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName "ResourceGroup" -T ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

New-AzureRmResourceGroupDeployment : 2:50:48 PM - Error: Code=InvalidCIDRNotation; Message=The address prefix 10.66.64.1/22 in resource
/subscriptions/9ef157b4-5cc4-4734-82aa-c8acfaa3f69d/resourceGroups/ResourceGroup/providers/Microsoft.Network/localNetworkGateways/tden-fort-LocalGateway has
an invalid CIDR notation. For the given prefix length, the address prefix should be 10.66.64.0/22.
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName "ResourceGroup" -T ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

New-AzureRmResourceGroupDeployment : The deployment validation failed
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName "ResourceGroup" -T ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeployment], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

**Comment by rsanderson2350** [comment]
It appears in your existing configuration (classic / ASM) that you selected an resource that has 10.66.64.1/22 configured as a CIDR.  Classic / ASM didn't validate this as well, and now ARM is validating this.  I would modify your export.json file to correct the "10.66.64.1/22" to "10.66.64.0/22" and then try to run your template again.  10.66.64.1/22 is an incorrect CIDR notation and needs to be corrected.

**Comment by ch40sth30ry** [comment]
Thank you! I should have recognized that as the problem! Tried with the corrected CIDR notation and the migration went fine. Thanks again!
