### ISSUE TITLE
error accesing azure account. This error begin appears last saturday

### ISSUE THREAD

**Issue by jzeledon** [Azure/migAz#88]
{"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"User was not found."}}}

Error en el servidor remoto: (403) Prohibido.

   en MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__84.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en MigAz.Azure.AzureRetriever.<GetAzureARMResources>d__83.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MigAz.Azure.AzureRetriever.<GetAzureARMDomains>d__53.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MigAz.Azure.AzureTenant.<InitializeChildren>d__16.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---

---------------------------------------------------
In other suscription

6/10/2017 12:11:02 p.m.   GetAzureRestResponse  Xd0e2cb0-5352-4c8e-beeb-b4b1X495cc03https://management.core.windows.net/Xca0e434-284b-4efd-bbc0-411X20a47c3b/rolesizes  EXCEPTION Error en el servidor remoto: (403) Prohibido.
26/10/2017 12:11:02 p.m.   ASM403ForbiddenExceptionDialog  <Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

Error en el servidor remoto: (403) Prohibido.

   en MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__84.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en MigAz.Azure.AzureRetriever.<GetAzureAsmResources>d__82.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MigAz.Azure.AzureRetriever.<GetAzureASMRoleSizes>d__37.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en MigAz.Azure.AzureRetriever.<BindAsmResources>d__85.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MigAz.Migrators.AsmToArm.<BindAsmResources>d__62.MoveNext()

**Comment by jzeledon** [comment]
Solve with issue #62

**Comment by rsanderson2350** [comment]
Thanks @jzeledon, glad you found the resolution with #62.
