### ISSUE TITLE
Error while enumerating ASM resources

### ISSUE THREAD

**Issue by kreuzhofer** [Azure/migAz#90]
I got this error today when logging into my subscription and enumerating ASM resources:

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei MigAz.Azure.AzureRetriever.<BindAsmResources>d__85.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MigAz.Migrators.AsmToArm.<BindAsmResources>d__62.MoveNext()

**Comment by rsanderson2350** [comment]
This may have been the same issue that was just resolved in which the source code had a variable problem when loading and ASM Probe.  If you are still able to verify, it would be good to get confirmation with v2.3.0.1 or later to validate if this is still an issue.

**Comment by rsanderson2350** [comment]
Proceeding to close for now.  Please advise if there is any further issue enumerating ASM resources.  v2.4.2.1 is the latest release.
