### ISSUE TITLE
The template deployment is not valid according to the validation procedure.

### ISSUE THREAD

**Issue by samerghneim** [Azure/migAz#91]
Hello, 

I'm facing this issue deploying a template I got from migaz. 
Test-AzureRmResourceGroupDeployment -ResourceGroupName "testrg" -TemplateFile "templatelocation"

Code    : InvalidTemplateDeployment
Message : The template deployment '156ed196-463d-4001-9ad9-c114701c4c27' is not valid according to the validation procedure. The tracking id is 
          'a19e7526-ccaa-4a8c-8041-cb0821526aad'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
Details : {Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PSResourceManagerError}

Kindly help

**Comment by rsanderson2350** [comment]
Consider using the -debug switch on the PowerShell command to get further output.  Further detail will need to be obtained/provided to know what about the template is invalid.
