### ISSUE TITLE
Cannot convert CloudPageBlob to CloudBlob during copy.

### ISSUE THREAD

**Issue by GiulianoBarco** [Azure/migAz#96]
Hello,
I'm moving my vms from ASM to ARM with MigAz. All works as expected till I run the script to snapshot and copy the VHDs.
[BlobCopy.zip](https://github.com/Azure/migAz/files/1557216/BlobCopy.zip)
[copyblobdetails.zip](https://github.com/Azure/migAz/files/1557217/copyblobdetails.zip)

I get this errors:
Cannot convert the "Microsoft.WindowsAzure.Storage.Blob.CloudPageBlob" value of type
"Microsoft.WindowsAzure.Storage.Blob.CloudPageBlob" to type "Microsoft.WindowsAzure.Storage.Blob.CloudBlob".
At C:\MigAz v2.2.14.0\Infostudi3\BlobCopy.ps1:60 char:9
+         $snapshot = [Microsoft.WindowsAzure.Storage.Blob.CloudBlob] $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException

Start-AzureStorageBlobCopy : Cannot bind parameter 'CloudBlob'. Cannot convert the
"Microsoft.WindowsAzure.Commands.Common.Storage.ResourceModel.AzureStorageBlob" value of type
"Microsoft.WindowsAzure.Commands.Common.Storage.ResourceModel.AzureStorageBlob" to type
"Microsoft.WindowsAzure.Storage.Blob.CloudBlob".
At C:\MigAz v2.2.14.0\Infostudi3\BlobCopy.ps1:63 char:73
+ ... torageBlobCopy -Context $source_context -ICloudBlob $snapshot -DestCo ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-AzureStorageBlobCopy], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.Start
   AzureStorageBlobCopy

What's wrong?
Many thanks.
Giuliano

**Comment by jantorep** [comment]
Hello

Im having the same issue here with a ASM to ARM migration. Im stuck and might need to move the disks manualy.

Regards
Jan-Tore Pedersen

**Comment by rsanderson2350** [comment]
It appears there was a change in newer Syntax / Object models and there is no need to cast the object (as [Start-AzureStorageBlobCopy ](https://docs.microsoft.com/en-us/powershell/module/azure.storage/start-azurestorageblobcopy?view=azurermps-5.1.1)can directly accept the ICloudBlob value without cast needed).  We do anticipate releasing a permanent fix this weekend as part of a new version release that will support Azure Managed Disks.

For an immediate fix, you can overlay the updated [BlobCopy.ps1](https://github.com/Azure/migAz/blob/master/MigAz.Azure/Generator/BlobCopy.ps1) file in the output directory after MigAz does the export (NOTE: MigAz overrides this file each time the template is exported.)
