### ISSUE TITLE
"Object reference not set to an instance of an object" error due to an improperly configured ASM Load Balancer

### ISSUE THREAD

**Issue by stephgou** [Azure/migAz#97]
Hi,
MigAz was unable to discover the existing infrastructure because of an improperly configured ASM load balancer and was displaying the error message : "object reference not set to an instance of an object"

I have just added a "try and catch" in the corresponding code in AzureRetriever.cs file (line 1706) to catch this error without stopping the whole analysis :

                                    if (targetProbe == null)
                                    {
                                        try
                                        {
                                            targetProbe = new Azure.MigrationTarget.Probe();
                                            targetProbe.Name = inputendpoint.SelectSingleNode("LoadBalancedEndpointSetName").InnerText;
                                            targetProbe.Port = Int32.Parse(probenode.SelectSingleNode("Port").InnerText);
                                            targetProbe.Protocol = probenode.SelectSingleNode("Protocol").InnerText;
                                            targetLoadBalancer.Probes.Add(targetProbe);
                                        }
                                        catch (Exception e)
                                        {
                                            System.Diagnostics.Trace.Write(e.InnerException);
                                        }                            
                                    }
Then I was able to generate the ARM file. 
So may be this error (and potential other ones due to improperly configured Azure ressources) could be catched for logging and not throwing an exception that prevents the script going till the end ?

Thanks a lot for your very usefull tool !
Merry Christmas !
Stéphane

**Comment by rsanderson2350** [comment]
Thank you Stéphane, hope you had a great holiday season.
