### ISSUE TITLE
MigAz v2.2.14.0 doesn't save Options.

### ISSUE THREAD

**Issue by GustiM** [Azure/migAz#99]
I open MigAz and change the Options, but once I close the Options screen, the default options are back again.
I installed it in Windows 10.

I will edit the file MigAz.exe.config and see if I can set the options I want during a migration and then remain the same for next migrations.

**Comment by rsanderson2350** [comment]
Ensure you are clicking the "OK" button at the bottom of the options dialog screen, as this is the button that contains the logic to actually save your settings.  Clicking the top right X to close the form doesn't contain the save logic.  I'll look to include this as a fix soon.

**Comment by GustiM** [comment]
Thanks for the fast response.
I don’t see any OK button at the bottom of the options dialog screen. Screen shot below:

[cid:image001.png@01D38640.A56DECF0]

Gusti Matei
-----------------
Sr Solution Designer - Infrastructure
Cooperators Group Limited
519-824-4400 #302189, Cell: 519-241-5364

**Comment by rsanderson2350** [comment]
You might try attaching your image directly via GitHub, as I'm not seeing it (only seeing the cid:image001.png tag above).  I'm trying to locate a previous issue, but it must have been in the previous GitHub repository for MigAz before it moved here.  I believe we had one other previous report that would be similar.  The form should look like the attached image.  

<img width="446" alt="options" src="https://user-images.githubusercontent.com/16927960/34630094-fc559e70-f227-11e7-9992-0cd180454616.png">

Do you have any Windows screen scaling changes applied to your screen settings?  The [AutoScale property](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.autoscalemode?view=netframework-4.7.1) of the options dialog is currently set to "Font", which indicates that "Controls scale relative to the dimensions of the font the classes are using, which is typically the system font".

**Comment by rsanderson2350** [comment]
Issue scope remaining - investigate why options dialog appears rescaled / resized to some users, causing at least the OK and Cancel buttons to not be visible.
